import type { ImageKey } from '../../shared/images'

/** Textes alternatifs des images (E80). Les images hero sont d’ambiance et restent masquées pour les lecteurs d’écran, toutes les autres images portent ce texte. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Agente d’entretien de dos passant la serpillière sur le granit mouillé de l’entrée d’un immeuble, avec boîtes aux lettres, ascenseur et chariot de nettoyage.',
  'hero-leistungen': 'Chariot de nettoyage entièrement équipé dans le couloir en linoléum d’une école; plus loin, une collaboratrice nettoie une poignée de porte.',
  'hero-unterhaltsreinigung': 'Agente d’entretien de dos nettoyant l’escalier en pierre reconstituée d’un immeuble, avec un seau rouge et un range-chaussures.',
  'hero-bueroreinigung': 'Agente d’entretien passant l’aspirateur le soir entre les postes de travail d’un bureau paysager.',
  'hero-umzugsreinigung': 'Nettoyage de fin de bail dans un appartement vide : une collaboratrice nettoie les façades de la cuisine, le four est ouvert, devant un seau et un escabeau.',
  'hero-baureinigung': 'Collaborateur aspirant la poussière de chantier dans un bâtiment neuf avant la remise, avec film de protection, seau et spatule.',
  'hero-fenster-fassaden': 'Laveur de vitres sur un escabeau lavant la grande vitre d’un immeuble de bureaux avec un mouilleur.',
  'hero-industrie-hallen': 'Collaborateur nettoyant le sol en béton d’un entrepôt entre des rayonnages à palettes avec une autolaveuse.',
  'hero-hauswartung': 'Concierge en tournée de contrôle vérifiant un manomètre dans la chaufferie d’un immeuble, sa caisse à outils à côté.',
  'hero-aussen-gruenflaechen': 'Collaborateur tondant la pelouse d’un lotissement, à côté d’une brouette d’herbe coupée et d’un râteau.',
  'hero-facility-services': 'Une collaboratrice avec une liste de contrôle et une cliente parcourent ensemble le couloir d’un immeuble de bureaux lors d’une remise.',
  'hero-premium': 'Collaboratrice entretenant un buffet en bois dans le séjour d’une villa au sol en pierre naturelle, avec vue sur le jardin.',
  'hero-premium-luxusimmobilien': 'Collaboratrice nettoyant le sol en calcaire clair du hall d’entrée d’une villa avec escalier en chêne.',
  'hero-premium-privatjet': 'Collaboratrice aspirant la moquette entre les sièges en cuir dans la cabine d’un avion d’affaires.',
  'hero-premium-yacht': 'Membre d’équipage frottant le pont en teck d’un yacht à moteur dans le port d’un lac de Suisse centrale.',
  'hero-einzugsgebiet': 'Vue depuis un coteau sur une vallée avec quartiers d’habitation, entreprises et voies ferrées jusqu’à un lac et aux montagnes de Suisse centrale.',
  'hero-ueber-uns': 'Collaboratrice préparant le chariot de nettoyage pour la journée dans le local de matériel, avec étagères de chiffons et d’appareils.',
  'hero-kontakt': 'Petit bureau avec table de travail, ordinateur portable, téléphone, bloc-notes et tasse de café, prêt pour le prochain appel.',
  'hero-ratgeber': 'Couloir de cave fraîchement nettoyé d’un immeuble avec compartiments en bois; au fond, une collaboratrice passe la serpillière.',
  'hero-artikel-reinigungsfirma': 'Lors d’une visite, un client montre les bureaux à une collaboratrice munie d’un porte-documents.',
  'hero-artikel-kosten': 'Mains montrant un plan d’étage sur une table en bois, à côté d’un mètre pliant, d’un bloc-notes et d’une tasse de café.',
  'hero-recht': 'Cage d’escalier calme et propre d’un immeuble, avec marches en pierre reconstituée et fenêtre.',
  'hero-kanton-luzern': 'Rive d’un lac en Suisse centrale avec promenade, bateaux, maisons sur le coteau et montagnes en arrière-plan.',
  'hero-kanton-zug': 'Promenade au bord d’un lac en Suisse centrale avec immeubles sur la rive et une montagne de l’autre côté du lac.',
  'hero-kanton-aargau': 'Petite ville au bord d’une rivière avec maisons de la vieille ville, clocher, pont de pierre et collines boisées.',
  'hero-kanton-nidwalden': 'Village de Suisse centrale avec église, prairies et montagnes, un lac en arrière-plan.',
  'hero-kanton-obwalden': 'Village au bord d’un lac en Suisse centrale avec église, prairies et montagnes se reflétant dans l’eau calme.',
  'detail-unterhaltsreinigung': 'Main gantée de gris essuyant la main courante en bois de la cage d’escalier avec un chiffon microfibre.',
  'detail-bueroreinigung': 'Mains gantées vidant une corbeille de bureau dans le sac poubelle du chariot de nettoyage.',
  'detail-umzugsreinigung': 'Mains en gants jaunes nettoyant l’intérieur d’un four lors d’un nettoyage de fin de bail, devant la plaque sale.',
  'detail-baureinigung': 'Mains en gants de travail retirant le film de protection d’un cadre de fenêtre neuf, un grattoir à vitres sur la tablette.',
  'detail-fenster-fassaden': 'Mains passant la raclette sur une vitre savonnée, le mouilleur dans l’autre main.',
  'detail-industrie-hallen': 'Autolaveuse nettoyant le sol en béton entre des rayonnages à palettes, guidée par le collaborateur.',
  'detail-hauswartung': 'Concierge changeant l’ampoule du plafonnier dans la buanderie d’un immeuble.',
  'detail-aussen-gruenflaechen': 'Collaborateur ratissant les feuilles mortes sur la pelouse d’un lotissement, à côté du conteneur à déchets verts.',
  'detail-facility-services': 'Mains cochant une liste de contrôle dans le dépôt de matériel, devant des étagères de chiffons et de produits.',
  'detail-premium-luxusimmobilien': 'Mains en gants noirs entretenant un lavabo en pierre naturelle à côté d’une robinetterie en laiton.',
  'detail-premium-privatjet': 'Mains gantées essuyant la table en loupe de bois dans la cabine d’un avion d’affaires.',
  'detail-premium-yacht': 'Mains gantées polissant un taquet en inox sur le pont en teck d’un yacht au port.',
  'hero-grundreinigung': 'Collaboratrice passant une monobrosse sur le sol en pierre naturelle d’un hall d’entrée, à côté d’un aspirateur à eau et d’un seau.',
  'detail-grundreinigung': 'Monobrosse travaillant avec de la mousse de nettoyage sur un sol en pierre naturelle usé.',
  // Motifs supplémentaires par page de prestation et Premium (E84) : deuxième ligne en zigzag et questions
  'szene-unterhaltsreinigung': 'Agente d’entretien essuyant la paroi en inox de la cabine d’ascenseur d’un immeuble, le chariot de nettoyage devant l’ascenseur.',
  'frage-unterhaltsreinigung': 'Une gérante montre à une collaboratrice munie d’un bloc-notes le local de nettoyage au sous-sol, où appareils et produits peuvent être rangés.',
  'szene-bueroreinigung': 'Collaboratrice essuyant le soir les accoudoirs des chaises dans la salle d’attente d’un cabinet, à côté de la réception et du chariot de nettoyage.',
  'frage-bueroreinigung': 'À l’entrée du bureau, un client remet à une collaboratrice munie d’un bloc-notes le badge d’accès pour le nettoyage.',
  'szene-sonderreinigungen': 'Collaboratrice à genoux frottant les joints du carrelage devant les cabines WC de sanitaires carrelés, à côté d’un seau et d’un vaporisateur.',
  'frage-sonderreinigungen': 'Lors de la visite d’une surface de bureaux vide, une collaboratrice examine le revêtement de sol usé sous le regard du gérant.',
  'szene-umzugsreinigung': 'Lors du nettoyage de fin de bail, une collaboratrice frotte le sol du balcon de l’appartement vide, à côté d’un seau et d’une pelle à feuilles.',
  'frage-umzugsreinigung': 'État des lieux dans l’appartement vide : la gérante montre le cadre de fenêtre, la collaboratrice le note sur son bloc-notes.',
  'szene-baureinigung': 'Nettoyage grossier dans le gros œuvre : un collaborateur balaie les gravats entre les murs en béton, à côté d’un seau et d’une brouette.',
  'frage-baureinigung': 'Un chef de chantier casqué, plan roulé en main, montre à une collaboratrice munie d’un bloc-notes le couloir d’un bâtiment neuf avant la remise.',
  'szene-fenster-und-fassadenreinigung': 'Laveur de vitres nettoyant depuis la pelouse une fenêtre du premier étage avec une perche télescopique à eau, le tuyau allant de l’appareil d’eau pure à la brosse.',
  'frage-fenster-und-fassadenreinigung': 'Lors d’un rendez-vous au bureau, un collaborateur ouvre le vantail pour vérifier si l’extérieur de la vitre est accessible depuis l’intérieur, la main du client sur le cadre.',
  'szene-industrie-und-hallenreinigung': 'Collaborateur aspirant les copeaux métalliques autour d’une machine dans un atelier de production avec un aspirateur industriel.',
  'frage-industrie-und-hallenreinigung': 'Lors de la visite de la halle, une collaboratrice en gilet de signalisation mesure les voies de circulation avec une roue de mesure, le chef d’exploitation marche à côté d’elle.',
  'szene-hauswartung': 'Concierge tirant le matin un conteneur à déchets depuis l’emplacement de collecte d’un lotissement jusqu’à la rue.',
  'frage-hauswartung': 'Lors de la visite, un représentant des propriétaires montre au concierge le luminaire de l’entrée.',
  'szene-aussen-und-gruenflaechenpflege': 'Collaborateur taillant la haie le long d’un chemin dans un lotissement, les déchets de taille tombant sur une bâche, à côté de la brouette.',
  'frage-aussen-und-gruenflaechenpflege': 'Avant la taille, une collaboratrice cherche des nids d’oiseaux dans la haie, la gérante regarde, le taille-haie posé sur le chemin.',
  'szene-facility-services': 'Devant l’entrée d’un immeuble commercial, un concierge balaie les feuilles sur le parvis pendant qu’une collègue nettoie la porte vitrée.',
  'frage-facility-services': 'À la table de réunion, un client et une collaboratrice parcourent le plan de situation de l’immeuble, avec les bâtiments, les chemins et les espaces verts.',
  'szene-luxusimmobilien': 'Collaboratrice essuyant avec un chiffon microfibre les façades mates de l’îlot de cuisine d’une villa.',
  'frage-luxusimmobilien': 'Lors de la visite d’une villa, la propriétaire montre à la collaboratrice la commode en noyer et les tableaux.',
  'szene-privatjet': 'Collaboratrice nettoyant les armoires en bois laqué brillant dans l’office d’un avion d’affaires, derrière elle la cabine et ses sièges en cuir.',
  'frage-privatjet': 'Dans le salon du hangar, un représentant de l’exploitant et une collaboratrice planifient le nettoyage de la cabine, l’avion visible derrière la vitre.',
  'szene-yacht': 'Depuis le ponton, une collaboratrice lave le pollen sur la coque d’un yacht à moteur avec une brosse douce.',
  'frage-yacht': 'Visite à la place d’amarrage : le propriétaire montre à un collaborateur sur le ponton le pont en teck de son yacht à moteur.',
  // Images de titre des nouveaux articles du guide (vague 2)
  'hero-artikel-pflichtenheft': 'Concierge muni d’un bloc-notes contrôlant le plafonnier lors de sa ronde dans la cage d’escalier d’un immeuble.',
  'hero-artikel-wohnungsabgabe': 'Appartement locatif vide et fraîchement nettoyé, avec parquet, avant l’état des lieux, les clés posées sur la tablette de fenêtre.',
  'hero-artikel-bodenarten': 'Seuil où la pierre naturelle rencontre le linoléum et le parquet, à côté d’un balai à plat et d’un chariot de nettoyage.',
}
