import type { ImageKey } from '../../shared/images'

/** Textes alternatifs des images (E80). Les images hero sont d’ambiance et restent masquées pour les lecteurs d’écran, toutes les autres images portent ce texte. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Hall d’entrée lumineux avec escalier en pierre, un agent de nettoyage en tenue de travail gris foncé, vu de dos, lave le sol en terrazzo brillant.',
  'hero-leistungen': 'Chariot de nettoyage bien rangé avec seaux, chiffons en microfibre et balai à franges dans un couloir lumineux à façade vitrée.',
  'hero-unterhaltsreinigung': 'Agent de nettoyage, vu de dos, lave le sol dans la cage d’escalier d’un immeuble locatif, avec un seau à côté.',
  'hero-bueroreinigung': 'Open space moderne vide le soir, avec postes de travail bien rangés, lumière chaude et vue sur le lac et les montagnes.',
  'hero-sonderreinigungen': 'Appartement clair et vide pendant le nettoyage de fin de bail, avec un îlot de cuisine en pierre naturelle propre et de grandes fenêtres donnant sur le lac.',
  'hero-baureinigung': 'Bâtiment neuf avant la remise, avec de la poussière de chantier sur la chape, des seaux, une raclette et de grandes surfaces vitrées avec vue sur le lac et les montagnes.',
  'hero-fenster-fassaden': 'Laveur de vitres, vu de dos, nettoie une grande façade vitrée avec une perche télescopique et de l’eau pure.',
  'hero-industrie-hallen': 'Collaborateur avec casque et gilet haute visibilité, vu de dos, nettoie le sol d’un grand hall lumineux avec une autolaveuse.',
  'hero-hauswartung': 'Concierge avec une mallette à outils, vu de dos, lors d’une ronde de contrôle dans la cour intérieure verdoyante d’une résidence bien entretenue.',
  'hero-aussen-gruenflaechen': 'Haie fraîchement taillée, allée de gravier avec feuilles d’automne, pelouse et un râteau à feuilles sur une propriété bien entretenue au bord du lac.',
  'hero-facility-services': 'Mains tenant un porte-bloc et un stylo lors d’une remise, avec du matériel de nettoyage et une collaboratrice vue de dos à l’arrière-plan.',
  'hero-premium': 'Séjour d’une villa avec sol en pierre naturelle, canapé aux tons chauds et vue sur un lac entouré de montagnes au soleil couchant.',
  'hero-premium-luxusimmobilien': 'Mains gantées de noir polissent avec un chiffon en microfibre un sol en pierre naturelle sombre, devant un parquet à chevrons.',
  'hero-premium-privatjet': 'Cabine vide d’un jet privé avec sièges en cuir crème, boiserie en loupe et moquette, avec des sommets alpins visibles par les fenêtres.',
  'hero-premium-yacht': 'Pont en teck d’un yacht à moteur avec coussins clairs et rambarde en acier inoxydable sur un lac calme, avec des montagnes dans la lumière du soir.',
  'hero-einzugsgebiet': 'Vue aérienne de la Suisse centrale dans la lumière du matin, avec un long lac, des villages sur la rive, de la brume et des montagnes.',
  'hero-ueber-uns': 'Produits de nettoyage, chiffons, brosses, seaux et balai à franges soigneusement disposés sur une étagère en bois dans une pièce lumineuse.',
  'hero-kontakt': 'Hall d’entrée vide et lumineux d’un immeuble de bureaux avec sol en pierre, lambris en bois et porte vitrée.',
  'hero-ratgeber': 'Couloir ensoleillé et lumineux avec un sol brillant et poli, avec une vue sur un lac au bout.',
  'hero-artikel-reinigungsfirma': 'Mains tenant un porte-bloc et un stylo lors d’une visite des lieux dans une cage d’escalier lumineuse.',
  'hero-artikel-kosten': 'Plan d’étage sur une table en bois sombre avec un mètre pliant et un stylo, ainsi que des échantillons de matériaux en pierre et en bois.',
  'hero-recht': 'Escalier en pierre blanche avec des lignes nettes de lumière et d’ombre sur un mur blanc.',
  'hero-kanton-luzern': 'Paysage de rive au lac des Quatre-Cantons avec roseaux, pierres sur la rive et montagnes boisées dans la lumière du matin.',
  'hero-kanton-zug': 'Lac de Zoug avec des constructions résidentielles modernes sur la rive, un ponton et des montagnes à l’arrière-plan.',
  'hero-kanton-aargau': 'L’Aare traverse un paysage verdoyant, avec sur sa rive une localité bien entretenue et un clocher.',
  'hero-kanton-nidwalden': 'Rive du lac à Nidwald avec un village, un ponton et des montagnes vertes escarpées qui se reflètent dans l’eau calme.',
  'hero-kanton-obwalden': 'Lac de Sarnen à Obwald avec des prairies, des maisons sur le coteau et des montagnes en direction d’Engelberg à contre-jour.',
  'detail-unterhaltsreinigung': 'Mains gantées de gris nettoient la porte en acier inoxydable d’un ascenseur dans l’entrée d’un immeuble d’habitation.',
  'detail-bueroreinigung': 'Kitchenette de bureau propre avec façades en bois, plan de travail clair, tasses et plantes.',
  'detail-sonderreinigungen': 'Mains gantées nettoient les cadres de fenêtres et le verre avec un chiffon en microfibre lors d’un nettoyage en profondeur.',
  'detail-baureinigung': 'Mains gantées essuient la poussière de chantier d’une vitre, avec derrière un chantier avec échafaudage et un lac.',
  'detail-fenster-fassaden': 'Gros plan d’une raclette à vitres essuyant une vitre, avec un lac et des montagnes à l’arrière-plan.',
  'detail-industrie-hallen': 'Mains gantées de travail nettoient la surface en acier inoxydable d’une machine dans un hall de production.',
  'detail-hauswartung': 'Buanderie bien rangée d’une résidence avec trois machines à laver, un séchoir à linge, un panier et une étagère.',
  'detail-aussen-gruenflaechen': 'Mains gantées de travail taillent une haie de hêtre verte avec un taille-haie.',
  'detail-facility-services': 'Mains cochent une liste de contrôle sur un porte-bloc, avec un chariot de nettoyage et une étagère à l’arrière-plan.',
  'detail-premium-luxusimmobilien': 'Mains gantées de noir entretiennent un lavabo en pierre naturelle sombre à côté d’une robinetterie en laiton.',
  'detail-premium-privatjet': 'Mains gantées de clair entretiennent avec un chiffon doux le siège en cuir d’un jet privé.',
  'detail-premium-yacht': 'Mains gantées polissent la rambarde en acier inoxydable à côté de coussins clairs à bord d’un yacht sur un lac.',
  'hero-grundreinigung': 'Nettoyage en profondeur dans le hall d’entrée d’un immeuble de bureaux : une personne vue de dos polit le sol en pierre naturelle claire avec une monobrosse.',
  'detail-grundreinigung': 'Des mains gantées de gris frottent les joints entre des dalles de pierre claires lors d’un nettoyage en profondeur.',
}
