import type { ImageKey } from '../../shared/images'

/** Textes alternatifs des images (E80). Les images hero sont d’ambiance et restent masquées pour les lecteurs d’écran, toutes les autres images portent ce texte. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Agente d’entretien de dos passant la serpillière sur le granit mouillé de l’entrée d’un immeuble, avec boîtes aux lettres, ascenseur et chariot de nettoyage.',
  'hero-leistungen': 'Chariot de nettoyage entièrement équipé dans le couloir en linoléum d’une école; plus loin, une collaboratrice nettoie une poignée de porte.',
  'hero-unterhaltsreinigung': 'Agente d’entretien de dos nettoyant l’escalier en pierre reconstituée d’un immeuble, avec un seau rouge et un range-chaussures.',
  'hero-bueroreinigung': 'Agente d’entretien passant l’aspirateur le soir entre les postes de travail d’un bureau paysager.',
  'hero-sonderreinigungen': 'Nettoyage de fin de bail dans un appartement vide: une collaboratrice nettoie les façades de la cuisine, le four est ouvert, devant un seau et un escabeau.',
  'hero-baureinigung': 'Collaborateur aspirant la poussière de chantier dans un bâtiment neuf avant la remise, avec film de protection, seau et spatule.',
  'hero-fenster-fassaden': 'Laveur de vitres sur un escabeau lavant la grande vitre d’un immeuble de bureaux avec un mouilleur.',
  'hero-industrie-hallen': 'Collaborateur nettoyant le sol en béton d’un entrepôt entre des rayonnages à palettes avec une autolaveuse.',
  'hero-hauswartung': 'Concierge en tournée de contrôle vérifiant un manomètre dans la chaufferie d’un immeuble, sa caisse à outils à côté.',
  'hero-aussen-gruenflaechen': 'Collaborateur tondant la pelouse d’un lotissement, à côté d’une brouette d’herbe coupée et d’un râteau.',
  'hero-facility-services': 'Une collaboratrice avec une liste de contrôle et une cliente parcourent ensemble le couloir d’un immeuble de bureaux lors d’une remise.',
  'hero-premium': 'Collaboratrice entretenant un buffet en bois dans le séjour d’une villa au sol en pierre naturelle, avec vue sur le jardin.',
  'hero-premium-luxusimmobilien': 'Collaboratrice nettoyant le sol en calcaire clair du hall d’entrée d’une villa avec escalier en chêne.',
  'hero-premium-privatjet': 'Collaboratrice aspirant la moquette entre les sièges en cuir dans la cabine d’un avion d’affaires.',
  'hero-premium-yacht': 'Membre d’équipage frottant le pont en teck d’un yacht à moteur dans un port du lac des Quatre-Cantons.',
  'hero-einzugsgebiet': 'Vue depuis un coteau sur la vallée de la Reuss avec quartiers d’habitation, entreprises et voies ferrées jusqu’au lac et au Pilate.',
  'hero-ueber-uns': 'Collaboratrice préparant le chariot de nettoyage pour la journée dans le local de matériel, avec étagères de chiffons et d’appareils.',
  'hero-kontakt': 'Petit bureau avec table de travail, ordinateur portable, téléphone, bloc-notes et tasse de café, prêt pour le prochain appel.',
  'hero-ratgeber': 'Couloir de cave fraîchement nettoyé d’un immeuble avec compartiments en bois; au fond, une collaboratrice passe la serpillière.',
  'hero-artikel-reinigungsfirma': 'Lors d’une visite, un client montre les bureaux à une collaboratrice munie d’un porte-documents.',
  'hero-artikel-kosten': 'Mains montrant un plan d’étage sur une table en bois, à côté d’un mètre pliant, d’un bloc-notes et d’une tasse de café.',
  'hero-recht': 'Cage d’escalier calme et propre d’un immeuble, avec marches en pierre reconstituée et fenêtre.',
  'hero-kanton-luzern': 'Rive du lac à Lucerne avec promenade, bateaux, maisons sur le coteau et le Pilate en arrière-plan.',
  'hero-kanton-zug': 'Promenade au bord du lac de Zoug avec immeubles sur la rive et le Rigi de l’autre côté du lac.',
  'hero-kanton-aargau': 'Petite ville au bord de l’Aar avec maisons de la vieille ville, clocher, pont de pierre et collines du Jura.',
  'hero-kanton-nidwalden': 'Village de Nidwald avec église, prairies et montagnes, le lac des Quatre-Cantons en arrière-plan.',
  'hero-kanton-obwalden': 'Village au bord du lac de Sarnen, en Obwald, avec église, prairies et montagnes se reflétant dans l’eau calme.',
  'detail-unterhaltsreinigung': 'Main gantée de gris essuyant la main courante en bois de la cage d’escalier avec un chiffon microfibre.',
  'detail-bueroreinigung': 'Mains gantées vidant une corbeille de bureau dans le sac poubelle du chariot de nettoyage.',
  'detail-sonderreinigungen': 'Mains en gants jaunes nettoyant l’intérieur d’un four lors d’un nettoyage de fin de bail, devant la plaque sale.',
  'detail-baureinigung': 'Mains en gants de travail retirant le film de protection d’un cadre de fenêtre neuf, un grattoir à vitres sur la tablette.',
  'detail-fenster-fassaden': 'Mains passant la raclette sur une vitre savonnée, le mouilleur dans l’autre main.',
  'detail-industrie-hallen': 'Autolaveuse nettoyant le sol en béton entre des rayonnages à palettes, guidée par le collaborateur.',
  'detail-hauswartung': 'Concierge changeant l’ampoule du plafonnier dans la buanderie d’un immeuble.',
  'detail-aussen-gruenflaechen': 'Collaborateur ratissant les feuilles mortes sur la pelouse d’un lotissement, à côté du conteneur à déchets verts.',
  'detail-facility-services': 'Mains cochant une liste de contrôle dans le dépôt de matériel, devant des étagères de chiffons et de produits.',
  'detail-premium-luxusimmobilien': 'Mains en gants noirs entretenant un lavabo en pierre naturelle à côté d’une robinetterie en laiton.',
  'detail-premium-privatjet': 'Mains gantées essuyant la table en loupe de bois dans la cabine d’un avion d’affaires.',
  'detail-premium-yacht': 'Mains gantées polissant un taquet en inox sur le pont en teck d’un yacht au port.',
  'hero-grundreinigung': 'Collaboratrice passant une monobrosse sur le sol en pierre naturelle d’un hall d’entrée, à côté d’un aspirateur à eau et d’un seau.',
  'detail-grundreinigung': 'Monobrosse travaillant avec de la mousse de nettoyage sur un sol en pierre naturelle usé.',
}
