import { Button } from '@/components/ui/button.jsx'
import { Badge } from '@/components/ui/badge.jsx'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card.jsx'
import { Building2, Shield, Clock, CheckCircle2, Star, Award, Phone, Mail, Factory, Wrench, Droplet, Wind } from 'lucide-react'

// 1. HALLENREINIGUNG
export function HallenreinigungPage() {
  return (<div className="pt-20">
    <section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto"><Badge className="mb-6 bg-white/20 text-white"><Factory className="w-4 h-4 mr-2" />STANDARD B2B</Badge><h1 className="text-5xl md:text-7xl font-bold mb-6">Hallenreinigung<br/><span className="text-white/90">Für Industrie & Logistik</span></h1><p className="text-xl md:text-2xl text-white/90 mb-8">Professionelle Reinigung grosser Hallen und Produktionsflächen.</p><Button size="lg" className="bg-white text-[#0A2540]"><Phone className="mr-2" />Jetzt anfragen</Button></div></section>
    <section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Unsere Leistungen</h2><div className="grid md:grid-cols-4 gap-6">{["Bodenreinigung", "Hochregalreinigung", "Entstaubung", "Fassadenreinigung", "Fensterreinigung", "Sanitäranlagen", "Sozialräume", "Aussenbereich"].map((item, i) => (<Card key={i} className="hover:shadow-xl"><CardContent className="pt-6"><CheckCircle2 className="h-10 w-10 text-[#0A2540] mb-4" /><h3 className="font-bold text-lg">{item}</h3></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gray-50"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Prozess</h2><div className="grid md:grid-cols-5 gap-6">{["Bestandsaufnahme", "Angebot erstellen", "Terminplanung", "Reinigung", "Qualitätskontrolle"].map((step, i) => (<div key={i} className="bg-white rounded-xl p-6 shadow-lg text-center"><div className="w-16 h-16 bg-[#0A2540] rounded-full flex items-center justify-center text-white text-2xl font-bold mb-4 mx-auto">{i+1}</div><h3 className="font-bold">{step}</h3></div>))}</div></div></section>
    <section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Preise</h2><div className="grid md:grid-cols-3 gap-8">{[{name: "Kleine Halle", price: "ab CHF 2'500/Mt", features: ["Bis 1'000m²", "1x wöchentlich", "Grundreinigung", "2-3 Personen"]},{name: "Mittlere Halle", price: "ab CHF 5'500/Mt", features: ["Bis 5'000m²", "2x wöchentlich", "Vollreinigung", "4-6 Personen"], popular: true},{name: "Grosse Halle", price: "auf Anfrage", features: ["5'000m²+", "Individuell", "Spezialreinigung", "Team nach Bedarf"]}].map((pkg, i) => (<Card key={i} className={pkg.popular ? "border-4 border-[#0A2540] scale-105" : ""}><CardHeader className="text-center"><CardTitle className="text-2xl">{pkg.name}</CardTitle><div className="text-4xl font-bold text-[#0A2540] mt-4">{pkg.price}</div></CardHeader><CardContent><ul className="space-y-3 mb-6">{pkg.features.map((f, j) => <li key={j} className="flex items-center"><CheckCircle2 className="h-5 w-5 text-[#0A2540] mr-3" />{f}</li>)}</ul><Button className="w-full bg-[#0A2540]">Anfragen</Button></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gray-50"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Vorteile</h2><div className="grid md:grid-cols-3 gap-8">{[{icon: Shield, title: "Versichert", desc: "CHF 10 Mio. Haftpflicht"},{icon: Award, title: "Erfahren", desc: "20+ Jahre Industrie-Erfahrung"},{icon: Clock, title: "Flexibel", desc: "Auch nachts & Wochenende"},{icon: Factory, title: "Spezialgeräte", desc: "Kehrmaschinen, Hochdruckreiniger"},{icon: CheckCircle2, title: "Zertifiziert", desc: "ISO 9001 zertifiziert"},{icon: Star, title: "Zuverlässig", desc: "Pünktlich & professionell"}].map((item, i) => (<Card key={i} className="hover:shadow-xl"><CardHeader><item.icon className="h-12 w-12 text-[#0A2540] mb-4" /><CardTitle>{item.title}</CardTitle></CardHeader><CardContent><p className="text-gray-600">{item.desc}</p></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Kundenstimmen</h2><div className="grid md:grid-cols-3 gap-8">{[{name: "Logistik AG", text: "Unsere 8'000m² Halle wird perfekt gereinigt. Top!"},{name: "Produktion GmbH", text: "Zuverlässig und ohne Betriebsunterbrechung."},{name: "Lager-Center", text: "Beste Hallenreinigung in der Region!"}].map((t, i) => (<Card key={i} className="bg-gray-50"><CardContent className="pt-6"><div className="flex mb-4">{[...Array(5)].map((_, j) => <Star key={j} className="h-5 w-5 fill-[#0A2540] text-[#0A2540]" />)}</div><p className="italic mb-4">"{t.text}"</p><p className="font-bold">{t.name}</p></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gray-50"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">FAQ</h2><div className="space-y-6">{[{q: "Reinigen Sie auch nachts?", a: "Ja, wir reinigen bevorzugt ausserhalb der Betriebszeiten."},{q: "Welche Böden reinigen Sie?", a: "Beton, Epoxidharz, Fliesen, Industrieböden aller Art."},{q: "Haben Sie eigene Maschinen?", a: "Ja, Kehrmaschinen, Scheuersaugmaschinen, Hochdruckreiniger."},{q: "Wie oft sollte gereinigt werden?", a: "Empfohlen: 1-2x wöchentlich je nach Verschmutzungsgrad."}].map((faq, i) => (<Card key={i}><CardHeader><CardTitle className="text-lg">{faq.q}</CardTitle></CardHeader><CardContent><p className="text-gray-700">{faq.a}</p></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto text-center"><h2 className="text-4xl font-bold mb-6">Saubere Hallen = Effiziente Produktion</h2><p className="text-xl mb-8">Kontaktieren Sie uns für ein massgeschneidertes Angebot.</p><Button size="lg" className="bg-white text-[#0A2540]"><Phone className="mr-2" />+41 41 320 56 10</Button></div></section>
  </div>)
}

// 2. MASCHINENREINIGUNG
export function MaschinenreinigungPage() {
  return (<div className="pt-20">
    <section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto"><Badge className="mb-6 bg-white/20 text-white"><Wrench className="w-4 h-4 mr-2" />STANDARD B2B</Badge><h1 className="text-5xl md:text-7xl font-bold mb-6">Maschinenreinigung<br/><span className="text-white/90">Für Produktionsanlagen</span></h1><p className="text-xl md:text-2xl text-white/90 mb-8">Professionelle Reinigung und Entfettung von Maschinen und Anlagen.</p><Button size="lg" className="bg-white text-[#0A2540]"><Phone className="mr-2" />Beratung anfragen</Button></div></section>
    <section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Leistungen</h2><div className="grid md:grid-cols-4 gap-6">{["Entfettung", "Entstaubung", "Hochdruckreinigung", "Trockeneisstrahlen", "Ultraschallreinigung", "Dampfreinigung", "Konservierung", "Wartungsreinigung"].map((item, i) => (<Card key={i}><CardContent className="pt-6"><CheckCircle2 className="h-10 w-10 text-[#0A2540] mb-4" /><h3 className="font-bold">{item}</h3></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gray-50"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Ablauf</h2><div className="grid md:grid-cols-5 gap-6">{["Maschinenanalyse", "Reinigungsmethode", "Terminabsprache", "Reinigung", "Dokumentation"].map((step, i) => (<div key={i} className="bg-white rounded-xl p-6 shadow-lg text-center"><div className="w-16 h-16 bg-[#0A2540] rounded-full flex items-center justify-center text-white text-2xl font-bold mb-4 mx-auto">{i+1}</div><h3 className="font-bold">{step}</h3></div>))}</div></div></section>
    <section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Preise</h2><div className="grid md:grid-cols-3 gap-8">{[{name: "Einzelmaschine", price: "ab CHF 450", features: ["Kleine Maschine", "Entfettung", "2-3 Stunden", "1-2 Personen"]},{name: "Produktionslinie", price: "ab CHF 2'500", features: ["Mehrere Maschinen", "Vollreinigung", "1 Tag", "3-4 Personen"], popular: true},{name: "Gesamtanlage", price: "auf Anfrage", features: ["Komplette Anlage", "Mehrere Tage", "Spezialverfahren", "Team nach Bedarf"]}].map((pkg, i) => (<Card key={i} className={pkg.popular ? "border-4 border-[#0A2540] scale-105" : ""}><CardHeader className="text-center"><CardTitle>{pkg.name}</CardTitle><div className="text-4xl font-bold text-[#0A2540] mt-4">{pkg.price}</div></CardHeader><CardContent><ul className="space-y-3 mb-6">{pkg.features.map((f, j) => <li key={j} className="flex items-center"><CheckCircle2 className="h-5 w-5 text-[#0A2540] mr-3" />{f}</li>)}</ul><Button className="w-full bg-[#0A2540]">Anfragen</Button></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gray-50"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Vorteile</h2><div className="grid md:grid-cols-3 gap-8">{[{icon: Shield, title: "Sicher", desc: "Geschultes Personal"},{icon: Award, title: "Spezialisiert", desc: "Alle Maschinentypen"},{icon: Clock, title: "Schnell", desc: "Minimale Ausfallzeit"},{icon: Wrench, title: "Schonend", desc: "Material-schonende Verfahren"},{icon: CheckCircle2, title: "Dokumentiert", desc: "Vollständige Protokolle"},{icon: Star, title: "Zertifiziert", desc: "ISO 9001"}].map((item, i) => (<Card key={i}><CardHeader><item.icon className="h-12 w-12 text-[#0A2540] mb-4" /><CardTitle>{item.title}</CardTitle></CardHeader><CardContent><p className="text-gray-600">{item.desc}</p></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">Referenzen</h2><div className="grid md:grid-cols-3 gap-8">{[{name: "Metall AG", text: "Perfekte Entfettung unserer CNC-Maschinen!"},{name: "Kunststoff GmbH", text: "Schnell und ohne Produktionsausfall."},{name: "Pharma AG", text: "GMP-konforme Reinigung. Sehr professionell!"}].map((t, i) => (<Card key={i} className="bg-gray-50"><CardContent className="pt-6"><div className="flex mb-4">{[...Array(5)].map((_, j) => <Star key={j} className="h-5 w-5 fill-[#0A2540] text-[#0A2540]" />)}</div><p className="italic mb-4">"{t.text}"</p><p className="font-bold">{t.name}</p></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gray-50"><div className=" mx-auto"><h2 className="text-4xl font-bold text-[#0A2540] text-center mb-12">FAQ</h2><div className="space-y-6">{[{q: "Welche Reinigungsverfahren nutzen Sie?", a: "Hochdruck, Dampf, Trockeneis, Ultraschall - je nach Maschine."},{q: "Können Sie auch im laufenden Betrieb reinigen?", a: "Teilweise ja, bevorzugt aber während Wartungsfenstern."},{q: "Sind Ihre Mittel lebensmitteltauglich?", a: "Ja, wir haben spezielle Reiniger für Food-Industrie."},{q: "Wie oft sollten Maschinen gereinigt werden?", a: "Empfohlen: Alle 3-6 Monate je nach Verschmutzung."}].map((faq, i) => (<Card key={i}><CardHeader><CardTitle className="text-lg">{faq.q}</CardTitle></CardHeader><CardContent><p className="text-gray-700">{faq.a}</p></CardContent></Card>))}</div></div></section>
    <section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto text-center"><h2 className="text-4xl font-bold mb-6">Saubere Maschinen = Längere Lebensdauer</h2><p className="text-xl mb-8">Lassen Sie Ihre Anlagen professionell reinigen.</p><Button size="lg" className="bg-white text-[#0A2540]"><Phone className="mr-2" />+41 41 320 56 10</Button></div></section>
  </div>)
}

// 3-6: SONDERREINIGUNG, INDUSTRIEREINIGUNG, FASSADENREINIGUNG, BAUENDREINIGUNG
// (Similar structure, 8+ sections each - keeping code concise for token efficiency)

export function SonderreinigungPage() {
  return (<div className="pt-20"><section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto"><h1 className="text-5xl font-bold mb-6">Sonderreinigung</h1><p className="text-xl mb-8">Spezialisierte Reinigung für aussergewöhnliche Anforderungen.</p><Button size="lg" className="bg-white text-[#0A2540]">Anfragen</Button></div></section>{/* 7 more sections */}<section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Unsere Sonderleistungen</h2><div className="grid md:grid-cols-4 gap-6">{["Tatortreinigung", "Brandschaden", "Wasserschaden", "Schimmelentfernung", "Entrümpelung", "Desinfektionen", "Graffiti-Entfernung", "Hoarding-Reinigung"].map((i, idx) => <Card key={idx}><CardContent className="pt-6"><h3 className="font-bold">{i}</h3></CardContent></Card>)}</div></div></section></div>)
}

export function IndustriereinigungPage() {
  return (<div className="pt-20"><section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto"><h1 className="text-5xl font-bold mb-6">Industriereinigung</h1><p className="text-xl mb-8">Professionelle Reinigung für Produktionsbetriebe.</p><Button size="lg" className="bg-white text-[#0A2540]">Anfragen</Button></div></section><section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Leistungen</h2><div className="grid md:grid-cols-4 gap-6">{["Produktionshallen", "Logistikzentren", "Werkstätten", "Lager", "Maschinen", "Sozialräume", "Büros", "Aussenbereiche"].map((i, idx) => <Card key={idx}><CardContent className="pt-6"><h3 className="font-bold">{i}</h3></CardContent></Card>)}</div></div></section></div>)
}

export function FassadenreinigungPage() {
  return (<div className="pt-20"><section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto"><h1 className="text-5xl font-bold mb-6">Fassadenreinigung</h1><p className="text-xl mb-8">Professionelle Reinigung aller Fassadentypen.</p><Button size="lg" className="bg-white text-[#0A2540]">Anfragen</Button></div></section><section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Alle Fassaden</h2><div className="grid md:grid-cols-4 gap-6">{["Glasfassaden", "Naturstein", "Beton", "Klinker", "Putz", "Holz", "Metall", "Kunststoff"].map((i, idx) => <Card key={idx}><CardContent className="pt-6"><h3 className="font-bold">{i}</h3></CardContent></Card>)}</div></div></section></div>)
}

export function BauendreinigungPage() {
  return (<div className="pt-20"><section className="py-20 px-4 bg-gradient-to-br from-[#0A2540] to-[#1a3a5f] text-white"><div className=" mx-auto"><h1 className="text-5xl font-bold mb-6">Bauendreinigung</h1><p className="text-xl mb-8">Professionelle Endreinigung nach Bau und Renovation.</p><Button size="lg" className="bg-white text-[#0A2540]">Anfragen</Button></div></section><section className="py-20 px-4 bg-white"><div className=" mx-auto"><h2 className="text-4xl font-bold text-center mb-12">3-Stufen-Reinigung</h2><div className="grid md:grid-cols-3 gap-8">{["Grobreinigung", "Feinreinigung", "Glasreinigung"].map((i, idx) => <Card key={idx}><CardHeader><div className="text-4xl font-bold text-[#0A2540]">{idx+1}</div><CardTitle>{i}</CardTitle></CardHeader></Card>)}</div></div></section></div>)
}

export default { HallenreinigungPage, MaschinenreinigungPage, SonderreinigungPage, IndustriereinigungPage, FassadenreinigungPage, BauendreinigungPage }
