import type { ImageKey } from '../../shared/images'

/** Testi alternativi delle immagini (E80). Le immagini hero sono d’atmosfera e restano nascoste per i lettori di schermo, tutte le altre immagini portano questo testo. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Addetta alle pulizie vista di spalle lava il pavimento in granito all’ingresso di un condominio con buche delle lettere e ascensore, accanto il carrello.',
  'hero-leistungen': 'Carrello delle pulizie completo nel corridoio in linoleum di una scuola; più avanti una collaboratrice pulisce una maniglia.',
  'hero-unterhaltsreinigung': 'Addetta vista di spalle pulisce la scala in pietra artificiale di un condominio, accanto un secchio rosso e una scarpiera.',
  'hero-bueroreinigung': 'Addetta passa l’aspirapolvere la sera tra le postazioni di un ufficio open space.',
  'hero-sonderreinigungen': 'Pulizia di fine locazione in un appartamento vuoto: una collaboratrice pulisce le ante della cucina, il forno è aperto, davanti secchio e scala.',
  'hero-baureinigung': 'Collaboratore aspira la polvere di cantiere in una nuova costruzione prima della consegna, accanto pellicola protettiva, secchio e spatola.',
  'hero-fenster-fassaden': 'Lavavetri su una scala lava la grande vetrata di un edificio per uffici con il vello.',
  'hero-industrie-hallen': 'Collaboratore pulisce il pavimento in cemento di un magazzino tra le scaffalature con una lavasciuga.',
  'hero-hauswartung': 'Custode durante il giro di controllo verifica un manometro nel locale caldaia di un condominio, accanto la cassetta degli attrezzi.',
  'hero-aussen-gruenflaechen': 'Collaboratore taglia il prato di un complesso residenziale, accanto una carriola con l’erba tagliata e un rastrello.',
  'hero-facility-services': 'Una collaboratrice con una lista di controllo e una cliente percorrono insieme il corridoio di un edificio per uffici durante una consegna.',
  'hero-premium': 'Collaboratrice cura una credenza in legno nel soggiorno di una villa con pavimento in pietra naturale, con vista sul giardino.',
  'hero-premium-luxusimmobilien': 'Collaboratrice lava il pavimento in pietra calcarea chiara nell’atrio di una villa con scala in rovere.',
  'hero-premium-privatjet': 'Collaboratrice aspira la moquette tra i sedili in pelle nella cabina di un aereo business.',
  'hero-premium-yacht': 'Membro dell’equipaggio strofina il ponte in teak di uno yacht a motore in un porto del lago dei Quattro Cantoni.',
  'hero-einzugsgebiet': 'Vista da un pendio sulla valle della Reuss con quartieri residenziali, aziende e ferrovia fino al lago e al Pilatus.',
  'hero-ueber-uns': 'Collaboratrice prepara il carrello delle pulizie per la giornata nel magazzino, accanto scaffali con panni e attrezzi.',
  'hero-kontakt': 'Piccolo ufficio con scrivania, portatile, telefono, blocco note e tazza di caffè, pronto per la prossima chiamata.',
  'hero-ratgeber': 'Corridoio della cantina di un condominio appena lavato con box in legno; in fondo una collaboratrice lavora con il mocio.',
  'hero-artikel-reinigungsfirma': 'Durante un sopralluogo un cliente mostra gli uffici a una collaboratrice con la cartellina.',
  'hero-artikel-kosten': 'Mani indicano una planimetria su un tavolo di legno, accanto metro pieghevole, blocco note e tazza di caffè.',
  'hero-recht': 'Vano scala tranquillo e pulito di un condominio con gradini in pietra artificiale e finestra.',
  'hero-kanton-luzern': 'Riva del lago a Lucerna con passeggiata, barche, case sul pendio e il Pilatus sullo sfondo.',
  'hero-kanton-zug': 'Lungolago sul lago di Zugo con edifici residenziali sulla riva e il Rigi sull’altra sponda.',
  'hero-kanton-aargau': 'Cittadina sull’Aare con case del centro storico, campanile, ponte in pietra e colline del Giura.',
  'hero-kanton-nidwalden': 'Villaggio nel Nidvaldo con chiesa, prati e montagne, sullo sfondo il lago dei Quattro Cantoni.',
  'hero-kanton-obwalden': 'Villaggio sul lago di Sarnen nell’Obvaldo con chiesa, prati e montagne che si specchiano nell’acqua calma.',
  'detail-unterhaltsreinigung': 'Mano con guanto grigio pulisce il corrimano in legno del vano scala con un panno in microfibra.',
  'detail-bueroreinigung': 'Mani con guanti svuotano il cestino di una postazione nel sacco dei rifiuti del carrello.',
  'detail-sonderreinigungen': 'Mani con guanti gialli puliscono l’interno di un forno durante la pulizia di fine locazione, davanti la teglia sporca.',
  'detail-baureinigung': 'Mani con guanti da lavoro tolgono la pellicola protettiva da un nuovo telaio, sul davanzale un raschietto per vetri.',
  'detail-fenster-fassaden': 'Mani passano il tergivetro sul vetro insaponato, nell’altra mano il vello.',
  'detail-industrie-hallen': 'Lavasciuga pulisce il pavimento in cemento tra le scaffalature, guidata dal collaboratore.',
  'detail-hauswartung': 'Custode cambia la lampadina della plafoniera nella lavanderia di un condominio.',
  'detail-aussen-gruenflaechen': 'Collaboratore rastrella le foglie autunnali sul prato di un complesso residenziale, accanto il contenitore del verde.',
  'detail-facility-services': 'Mani spuntano una lista di controllo nel magazzino, dietro scaffali con panni e detergenti.',
  'detail-premium-luxusimmobilien': 'Mani con guanti neri curano un lavabo in pietra naturale accanto a una rubinetteria in ottone.',
  'detail-premium-privatjet': 'Mani con guanti puliscono il tavolo in radica nella cabina di un aereo business.',
  'detail-premium-yacht': 'Mani con guanti lucidano una galloccia in acciaio inox sul ponte in teak di uno yacht nel porto.',
  'hero-grundreinigung': 'Collaboratrice guida una monospazzola sul pavimento in pietra naturale di un atrio, accanto un aspiraliquidi e un secchio.',
  'detail-grundreinigung': 'Monospazzola lavora con schiuma detergente su un pavimento in pietra naturale consumato.',
}
