import type { ImageKey } from '../../shared/images'

/** Testi alternativi delle immagini (E80). Le immagini hero sono d’atmosfera e restano nascoste per i lettori di schermo, tutte le altre immagini portano questo testo. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Atrio luminoso con scala in pietra, un addetto alle pulizie in abbigliamento da lavoro grigio scuro, visto di spalle, lava il pavimento in terrazzo lucido.',
  'hero-leistungen': 'Carrello per le pulizie ordinato con secchi, panni in microfibra e mocio in un corridoio luminoso con facciata in vetro.',
  'hero-unterhaltsreinigung': 'Addetto alle pulizie, visto di spalle, lava il pavimento nella tromba delle scale di una palazzina residenziale, con un secchio accanto.',
  'hero-bueroreinigung': 'Ufficio open space moderno e vuoto la sera, con postazioni di lavoro ordinate, luce calda e vista sul lago e sulle montagne.',
  'hero-sonderreinigungen': 'Appartamento luminoso e vuoto durante la pulizia finale, con un’isola cucina in pietra naturale pulita e grandi finestre affacciate sul lago.',
  'hero-baureinigung': 'Edificio nuovo prima della consegna, con polvere da cantiere sul massetto, secchi, un tergivetro e grandi superfici vetrate con vista sul lago e sulle montagne.',
  'hero-fenster-fassaden': 'Lavavetri, visto di spalle, pulisce una grande facciata in vetro con un’asta telescopica e acqua pura.',
  'hero-industrie-hallen': 'Collaboratore con casco e gilet ad alta visibilità, visto di spalle, pulisce il pavimento di un grande capannone luminoso con una lavasciuga pavimenti.',
  'hero-hauswartung': 'Custode con una cassetta degli attrezzi, visto di spalle, durante un giro di controllo nel cortile interno verde di una residenza ben curata.',
  'hero-aussen-gruenflaechen': 'Siepe appena potata, vialetto di ghiaia con foglie autunnali, prato e un rastrello per foglie in una proprietà ben curata sul lago.',
  'hero-facility-services': 'Mani con una tavoletta portablocco e una penna durante una consegna, con attrezzature per le pulizie e una collaboratrice vista di spalle sullo sfondo.',
  'hero-premium': 'Soggiorno di una villa con pavimento in pietra naturale, divano dai toni caldi e vista su un lago con montagne al sole della sera.',
  'hero-premium-luxusimmobilien': 'Mani con guanti neri lucidano con un panno in microfibra un pavimento in pietra naturale scura, davanti a un parquet a spina di pesce.',
  'hero-premium-privatjet': 'Cabina vuota di un jet privato con sedili in pelle color crema, rivestimenti in radica e moquette, con cime alpine visibili dai finestrini.',
  'hero-premium-yacht': 'Ponte in teak di uno yacht a motore con cuscini chiari e parapetto in acciaio inossidabile su un lago tranquillo, con montagne nella luce della sera.',
  'hero-einzugsgebiet': 'Vista aerea della Svizzera centrale nella luce del mattino, con un lago lungo, villaggi sulla riva, nebbia e montagne.',
  'hero-ueber-uns': 'Prodotti per le pulizie, panni, spazzole, secchi e mocio disposti con cura su uno scaffale in legno in una stanza luminosa.',
  'hero-kontakt': 'Atrio d’ingresso vuoto e luminoso di un edificio per uffici con pavimento in pietra, rivestimento in legno e porta a vetri.',
  'hero-ratgeber': 'Corridoio soleggiato e luminoso con pavimento lucido e levigato, con vista su un lago in fondo.',
  'hero-artikel-reinigungsfirma': 'Mani con una tavoletta portablocco e una penna durante un sopralluogo in una tromba delle scale luminosa.',
  'hero-artikel-kosten': 'Planimetria su un tavolo in legno scuro con un metro pieghevole e una penna, insieme a campioni di materiali in pietra e legno.',
  'hero-recht': 'Scala in pietra bianca con nette linee di luce e ombra su una parete bianca.',
  'hero-kanton-luzern': 'Paesaggio rivierasco sul lago dei Quattro Cantoni con canneti, pietre sulla riva e montagne boscose nella luce del mattino.',
  'hero-kanton-zug': 'Lago di Zugo con moderni edifici residenziali sulla riva, un pontile e montagne sullo sfondo.',
  'hero-kanton-aargau': 'L’Aare scorre attraverso un paesaggio verde, con sulla riva un insediamento ben curato e un campanile.',
  'hero-kanton-nidwalden': 'Riva del lago nel Nidvaldo con un villaggio, un pontile e montagne verdi scoscese che si specchiano nell’acqua calma.',
  'hero-kanton-obwalden': 'Lago di Sarnen nell’Obvaldo con prati, case sul pendio e montagne in direzione di Engelberg in controluce.',
  'detail-unterhaltsreinigung': 'Mani con guanti grigi puliscono la porta in acciaio inossidabile di un ascensore nell’area d’ingresso di un edificio residenziale.',
  'detail-bueroreinigung': 'Angolo cottura d’ufficio pulito con ante in legno, piano di lavoro chiaro, tazze e piante.',
  'detail-sonderreinigungen': 'Mani con guanti puliscono telai delle finestre e vetri con un panno in microfibra durante una pulizia a fondo.',
  'detail-baureinigung': 'Mani con guanti asciugano la polvere da cantiere da un vetro, con dietro un cantiere con ponteggio e un lago.',
  'detail-fenster-fassaden': 'Primo piano di un tergivetro che asciuga un vetro, con lago e montagne sullo sfondo.',
  'detail-industrie-hallen': 'Mani con guanti da lavoro puliscono la superficie in acciaio inossidabile di una macchina in un capannone di produzione.',
  'detail-hauswartung': 'Lavanderia ordinata di una residenza con tre lavatrici, uno stendibiancheria, un cesto e uno scaffale.',
  'detail-aussen-gruenflaechen': 'Mani con guanti da lavoro tagliano una siepe di faggio verde con un tagliasiepi.',
  'detail-facility-services': 'Mani spuntano una checklist su una tavoletta portablocco, con un carrello per le pulizie e uno scaffale sullo sfondo.',
  'detail-premium-luxusimmobilien': 'Mani con guanti neri curano un lavabo in pietra naturale scura accanto a un rubinetto in ottone.',
  'detail-premium-privatjet': 'Mani con guanti chiari curano con un panno morbido il sedile in pelle di un jet privato.',
  'detail-premium-yacht': 'Mani con guanti lucidano il parapetto in acciaio inossidabile accanto a cuscini chiari a bordo di uno yacht su un lago.',
}
