import type { ImageKey } from '../../shared/images'

/** Testi alternativi delle immagini (E80). Le immagini hero sono d’atmosfera e restano nascoste per i lettori di schermo, tutte le altre immagini portano questo testo. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Addetta alle pulizie vista di spalle lava il pavimento in granito all’ingresso di un condominio con buche delle lettere e ascensore, accanto il carrello.',
  'hero-leistungen': 'Carrello delle pulizie completo nel corridoio in linoleum di una scuola; più avanti una collaboratrice pulisce una maniglia.',
  'hero-unterhaltsreinigung': 'Addetta vista di spalle pulisce la scala in pietra artificiale di un condominio, accanto un secchio rosso e una scarpiera.',
  'hero-bueroreinigung': 'Addetta passa l’aspirapolvere la sera tra le postazioni di un ufficio open space.',
  'hero-umzugsreinigung': 'Pulizia di fine locazione in un appartamento vuoto: una collaboratrice pulisce le ante della cucina, il forno è aperto, davanti secchio e scala.',
  'hero-baureinigung': 'Collaboratore aspira la polvere di cantiere in una nuova costruzione prima della consegna, accanto pellicola protettiva, secchio e spatola.',
  'hero-fenster-fassaden': 'Lavavetri su una scala lava la grande vetrata di un edificio per uffici con il vello.',
  'hero-industrie-hallen': 'Collaboratore pulisce il pavimento in cemento di un magazzino tra le scaffalature con una lavasciuga.',
  'hero-hauswartung': 'Custode durante il giro di controllo verifica un manometro nel locale caldaia di un condominio, accanto la cassetta degli attrezzi.',
  'hero-aussen-gruenflaechen': 'Collaboratore taglia il prato di un complesso residenziale, accanto una carriola con l’erba tagliata e un rastrello.',
  'hero-facility-services': 'Una collaboratrice con una lista di controllo e una cliente percorrono insieme il corridoio di un edificio per uffici durante una consegna.',
  'hero-premium': 'Collaboratrice cura una credenza in legno nel soggiorno di una villa con pavimento in pietra naturale, con vista sul giardino.',
  'hero-premium-luxusimmobilien': 'Collaboratrice lava il pavimento in pietra calcarea chiara nell’atrio di una villa con scala in rovere.',
  'hero-premium-privatjet': 'Collaboratrice aspira la moquette tra i sedili in pelle nella cabina di un aereo business.',
  'hero-premium-yacht': 'Membro dell’equipaggio strofina il ponte in teak di uno yacht a motore nel porto di un lago della Svizzera centrale.',
  'hero-einzugsgebiet': 'Vista da un pendio su una valle con quartieri residenziali, aziende e ferrovia fino a un lago e alle montagne della Svizzera centrale.',
  'hero-ueber-uns': 'Collaboratrice prepara il carrello delle pulizie per la giornata nel magazzino, accanto scaffali con panni e attrezzi.',
  'hero-kontakt': 'Piccolo ufficio con scrivania, portatile, telefono, blocco note e tazza di caffè, pronto per la prossima chiamata.',
  'hero-ratgeber': 'Corridoio della cantina di un condominio appena lavato con box in legno; in fondo una collaboratrice lavora con il mocio.',
  'hero-artikel-reinigungsfirma': 'Durante un sopralluogo un cliente mostra gli uffici a una collaboratrice con la cartellina.',
  'hero-artikel-kosten': 'Mani indicano una planimetria su un tavolo di legno, accanto metro pieghevole, blocco note e tazza di caffè.',
  'hero-recht': 'Vano scala tranquillo e pulito di un condominio con gradini in pietra artificiale e finestra.',
  'hero-kanton-luzern': 'Riva di un lago nella Svizzera centrale con passeggiata, barche, case sul pendio e montagne sullo sfondo.',
  'hero-kanton-zug': 'Lungolago nella Svizzera centrale con edifici residenziali sulla riva e una montagna sull’altra sponda.',
  'hero-kanton-aargau': 'Cittadina su un fiume con case del centro storico, campanile, ponte in pietra e colline boscose.',
  'hero-kanton-nidwalden': 'Villaggio nella Svizzera centrale con chiesa, prati e montagne, sullo sfondo un lago.',
  'hero-kanton-obwalden': 'Villaggio in riva a un lago nella Svizzera centrale con chiesa, prati e montagne che si specchiano nell’acqua calma.',
  'detail-unterhaltsreinigung': 'Mano con guanto grigio pulisce il corrimano in legno del vano scala con un panno in microfibra.',
  'detail-bueroreinigung': 'Mani con guanti svuotano il cestino di una postazione nel sacco dei rifiuti del carrello.',
  'detail-umzugsreinigung': 'Mani con guanti gialli puliscono l’interno di un forno durante la pulizia di fine locazione, davanti la teglia sporca.',
  'detail-baureinigung': 'Mani con guanti da lavoro tolgono la pellicola protettiva da un nuovo telaio, sul davanzale un raschietto per vetri.',
  'detail-fenster-fassaden': 'Mani passano il tergivetro sul vetro insaponato, nell’altra mano il vello.',
  'detail-industrie-hallen': 'Collaboratore in abiti da lavoro grigi e guanti pulisce l’esterno di un carter macchina chiuso con un panno blu.',
  'detail-hauswartung': 'Custode cambia la lampadina della plafoniera nella lavanderia di un condominio.',
  'detail-aussen-gruenflaechen': 'Collaboratore rastrella le foglie autunnali sul prato di un complesso residenziale, accanto il contenitore del verde.',
  'detail-facility-services': 'Mani spuntano una lista di controllo nel magazzino, dietro scaffali con panni e detergenti.',
  'detail-premium-luxusimmobilien': 'Mani con guanti neri curano un lavabo in pietra naturale accanto a una rubinetteria in ottone.',
  'detail-premium-privatjet': 'Mani con guanti puliscono il tavolo in radica nella cabina di un aereo business.',
  'detail-premium-yacht': 'Mani con guanti lucidano una galloccia in acciaio inox sul ponte in teak di uno yacht nel porto.',
  'hero-grundreinigung': 'Collaboratrice guida una monospazzola sul pavimento in pietra naturale di un atrio, accanto un aspiraliquidi e un secchio.',
  'detail-grundreinigung': 'Monospazzola lavora con schiuma detergente su un pavimento in pietra naturale consumato.',
  // Motivi aggiuntivi per pagina di servizio e Premium (E84): seconda riga a zigzag e domande
  'szene-unterhaltsreinigung': 'Addetta alle pulizie pulisce la parete in acciaio inox della cabina dell’ascensore in un condominio, il carrello davanti all’ascensore.',
  'frage-unterhaltsreinigung': 'Un’amministratrice mostra a una collaboratrice con la cartellina il locale delle pulizie in cantina, dove si possono riporre attrezzi e detergenti.',
  'szene-bueroreinigung': 'Collaboratrice pulisce la sera i braccioli delle sedie nella sala d’attesa di uno studio, accanto la reception e il carrello delle pulizie.',
  'frage-bueroreinigung': 'All’ingresso dell’ufficio un cliente consegna a una collaboratrice con la cartellina il badge d’accesso per le pulizie.',
  'szene-sonderreinigungen': 'Collaboratrice in ginocchio strofina le fughe del pavimento davanti ai box WC di un locale sanitario piastrellato, accanto secchio e spruzzino.',
  'frage-sonderreinigungen': 'Durante il sopralluogo di una superficie per uffici vuota una collaboratrice controlla il pavimento consumato, l’amministratore osserva.',
  'szene-umzugsreinigung': 'Durante la pulizia di fine locazione una collaboratrice strofina il pavimento del balcone dell’appartamento vuoto, accanto secchio e paletta con foglie.',
  'frage-umzugsreinigung': 'Alla riconsegna nell’appartamento vuoto l’amministratrice indica il telaio della finestra, la collaboratrice lo annota sulla cartellina.',
  'szene-baureinigung': 'Pulizia grossolana al rustico: un collaboratore raccoglie i detriti tra le pareti in cemento, accanto secchio e carriola.',
  'frage-baureinigung': 'Un direttore dei lavori con casco e piano arrotolato mostra a una collaboratrice con la cartellina il corridoio di una nuova costruzione prima della consegna.',
  'szene-fenster-und-fassadenreinigung': 'Lavavetri pulisce dal prato una finestra del primo piano con un’asta telescopica ad acqua, il tubo va dall’apparecchio ad acqua pura fino alla spazzola.',
  'frage-fenster-und-fassadenreinigung': 'Durante un appuntamento in ufficio un collaboratore apre l’anta per verificare se il lato esterno del vetro si raggiunge dall’interno, la mano del cliente sul telaio.',
  'szene-industrie-und-hallenreinigung': 'Collaboratore aspira i trucioli metallici intorno a una macchina in un capannone di produzione con un aspiratore industriale.',
  'frage-industrie-und-hallenreinigung': 'Durante il sopralluogo nel capannone una collaboratrice con gilet ad alta visibilità misura le vie di transito con la rotella metrica, accanto a lei il responsabile di produzione.',
  'szene-hauswartung': 'Custode trascina al mattino un contenitore dei rifiuti dal punto di raccolta di un complesso residenziale alla strada.',
  'frage-hauswartung': 'Durante il sopralluogo un rappresentante dei proprietari mostra al custode la lampada all’ingresso dello stabile.',
  'szene-aussen-und-gruenflaechenpflege': 'Collaboratore pota la siepe lungo un sentiero di un complesso residenziale, i ritagli cadono su un telo, accanto la carriola.',
  'frage-aussen-und-gruenflaechenpflege': 'Prima della potatura una collaboratrice controlla se nella siepe ci sono nidi, l’amministratrice osserva, il tagliasiepi è appoggiato sul sentiero.',
  'szene-facility-services': 'Davanti all’ingresso di un edificio commerciale un custode spazza le foglie dal piazzale mentre una collega pulisce la porta a vetri.',
  'frage-facility-services': 'Al tavolo riunioni un cliente e una collaboratrice esaminano la planimetria della proprietà con edifici, percorsi e aree verdi.',
  'szene-luxusimmobilien': 'Collaboratrice pulisce con un panno morbido le ante opache dell’isola della cucina di una villa.',
  'frage-luxusimmobilien': 'Durante il giro di una villa la proprietaria mostra alla collaboratrice il cassettone in noce e i quadri.',
  'szene-privatjet': 'Collaboratrice pulisce i mobili in legno lucido nel galley di un aereo business, dietro la cabina con i sedili in pelle.',
  'frage-privatjet': 'Nella lounge dell’hangar un rappresentante dell’operatore di volo e una collaboratrice pianificano la pulizia della cabina, dietro il vetro l’aereo.',
  'szene-yacht': 'Dal pontile una collaboratrice lava il polline dallo scafo di uno yacht a motore con una spazzola morbida.',
  'frage-yacht': 'Sopralluogo all’ormeggio: il proprietario mostra a un collaboratore sul pontile il ponte in teak del suo yacht a motore.',
  // Immagini di copertina dei nuovi articoli della guida (fase 2)
  'hero-artikel-pflichtenheft': 'Custode con la cartellina controlla la plafoniera durante il giro di controllo nel vano scala di un condominio.',
  'hero-artikel-wohnungsabgabe': 'Appartamento in affitto vuoto e appena pulito con parquet prima della riconsegna, le chiavi sul davanzale.',
  'hero-artikel-bodenarten': 'Soglia dove la pietra naturale incontra linoleum e parquet, accanto un mop piatto e il carrello delle pulizie.',
}
