import type { ImageKey } from '../../shared/images'

/** Alt texts for the images (E80). Heroes are mood images and stay hidden from screen readers; all other images carry this text. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Bright entrance hall with a stone staircase; a cleaner in dark grey workwear, seen from behind, mops the glossy terrazzo floor.',
  'hero-leistungen': 'Tidy cleaning trolley with buckets, microfibre cloths and a mop in a bright corridor with a glass front.',
  'hero-unterhaltsreinigung': 'Cleaner, seen from behind, mops the floor in the stairwell of a block of flats, with a bucket beside them.',
  'hero-bueroreinigung': 'Empty modern open-plan office in the evening with tidy workstations, warm light and a view of the lake and mountains.',
  'hero-sonderreinigungen': 'Empty, bright flat during the final clean, with a clean natural stone kitchen island and large windows overlooking the lake.',
  'hero-baureinigung': 'New-build property before handover, with construction dust on the screed floor, buckets, a squeegee and large glazed areas with a view of the lake and mountains.',
  'hero-fenster-fassaden': 'Window cleaner, seen from behind, cleans a large glass façade with a telescopic pole and pure water.',
  'hero-industrie-hallen': 'Employee wearing a hard hat and hi-vis vest, seen from behind, cleans the floor of a large bright hall with a scrubber dryer.',
  'hero-hauswartung': 'Caretaker with a toolbox, seen from behind, on an inspection walk through the landscaped courtyard of a well-kept residential estate.',
  'hero-aussen-gruenflaechen': 'Freshly trimmed hedge, gravel path with autumn leaves, lawn and a leaf rake at a well-kept property by the lake.',
  'hero-facility-services': 'Hands holding a clipboard and pen during a handover, with cleaning equipment and a female employee seen from behind in the background.',
  'hero-premium': 'Living space in a villa with a natural stone floor, a sofa in warm tones and a view of a lake with mountains in the evening sun.',
  'hero-premium-luxusimmobilien': 'Hands in black gloves polish a dark natural stone floor with a microfibre cloth, in front of herringbone parquet flooring.',
  'hero-premium-privatjet': 'Empty cabin of a private jet with cream-coloured leather seats, burr wood trim and carpet, with alpine peaks visible through the windows.',
  'hero-premium-yacht': 'Teak deck of a motor yacht with light-coloured upholstery and a stainless steel railing on a calm lake, with mountains in the evening light.',
  'hero-einzugsgebiet': 'Aerial view of Central Switzerland in the morning light, with a long lake, villages on the shore, mist and mountains.',
  'hero-ueber-uns': 'Carefully arranged cleaning products, cloths, brushes, buckets and a mop on a wooden shelf in a bright room.',
  'hero-kontakt': 'Empty, bright entrance hall of an office building with a stone floor, wood panelling and a glass door.',
  'hero-ratgeber': 'Sunny, bright corridor with a glossy, polished floor and a view of a lake at the far end.',
  'hero-artikel-reinigungsfirma': 'Hands holding a clipboard and pen during a site visit in a bright stairwell.',
  'hero-artikel-kosten': 'Floor plan on a dark wooden table with a folding ruler and pen, alongside material samples of stone and wood.',
  'hero-recht': 'White stone staircase with clear lines of light and shadow against a white wall.',
  'hero-kanton-luzern': 'Shoreline landscape on Lake Lucerne with reeds, stones on the shore and wooded mountains in the morning light.',
  'hero-kanton-zug': 'Lake Zug with modern residential development on the shore, a boat jetty and mountains in the background.',
  'hero-kanton-aargau': 'The Aare flows through a green landscape, with a well-kept settlement and a church tower on its bank.',
  'hero-kanton-nidwalden': 'Lakeshore in Nidwalden with a village, a boat jetty and steep green mountains reflected in the calm water.',
  'hero-kanton-obwalden': 'Lake Sarnen in Obwalden with meadows, houses on the hillside and mountains towards Engelberg in the backlight.',
  'detail-unterhaltsreinigung': 'Hands in grey gloves clean the stainless steel door of a lift in the entrance area of a residential building.',
  'detail-bueroreinigung': 'Clean office kitchenette with wooden fronts, a light-coloured worktop, cups and plants.',
  'detail-sonderreinigungen': 'Hands in gloves clean window frames and glass with a microfibre cloth during a deep clean.',
  'detail-baureinigung': 'Hands in gloves wipe construction dust from a pane of glass, with a building site with scaffolding and a lake behind it.',
  'detail-fenster-fassaden': 'Close-up of a window squeegee wiping a pane of glass, with a lake and mountains in the background.',
  'detail-industrie-hallen': 'Hands in work gloves clean the stainless steel surface of a machine in a production hall.',
  'detail-hauswartung': 'Tidy laundry room of a residential estate with three washing machines, a clothes airer, a basket and a shelf.',
  'detail-aussen-gruenflaechen': 'Hands in work gloves trim a green beech hedge with a hedge trimmer.',
  'detail-facility-services': 'Hands tick off a checklist on a clipboard, with a cleaning trolley and shelf in the background.',
  'detail-premium-luxusimmobilien': 'Hands in black gloves care for a washbasin made of dark natural stone next to a brass tap.',
  'detail-premium-privatjet': 'Hands in light-coloured gloves care for the leather seat in a private jet with a soft cloth.',
  'detail-premium-yacht': 'Hands in gloves polish the stainless steel railing next to light-coloured upholstery on board a yacht on a lake.',
}
