import type { ImageKey } from '../../shared/images'

/** Alt texts for the images (E80). Heroes are mood images and stay hidden from screen readers; all other images carry this text. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Cleaner seen from behind mopping the wet granite floor in the entrance of a block of flats with letterboxes and a lift, the cleaning trolley beside her.',
  'hero-leistungen': 'Fully equipped cleaning trolley in the linoleum corridor of a school building; further back an employee cleans a door handle.',
  'hero-unterhaltsreinigung': 'Cleaner seen from behind mopping the artificial stone stairs in the stairwell of a block of flats, with a red bucket and a shoe rack beside her.',
  'hero-bueroreinigung': 'Cleaner vacuuming the carpet between the workstations of an open-plan office in the evening.',
  'hero-umzugsreinigung': 'End-of-tenancy cleaning in an empty rented flat: an employee cleans the kitchen fronts, the oven stands open, with a bucket and ladder in front.',
  'hero-baureinigung': 'Employee vacuuming construction dust from the floor of a new build before handover, with protective film, a bucket and a scraper beside him.',
  'hero-fenster-fassaden': 'Window cleaner on a stepladder washing the large pane of an office building with a strip washer.',
  'hero-industrie-hallen': 'Employee cleaning the concrete floor of a warehouse between pallet racks with a scrubber dryer.',
  'hero-hauswartung': 'Caretaker on an inspection round checking a pressure gauge in the boiler room of a block of flats, his toolbox beside him.',
  'hero-aussen-gruenflaechen': 'Employee mowing the lawn of a housing estate, with a wheelbarrow of grass cuttings and a rake beside him.',
  'hero-facility-services': 'An employee with a checklist and a client walk together through the corridor of an office building during a handover.',
  'hero-premium': 'Employee caring for a wooden sideboard in the living room of a villa with a natural stone floor, with a view into the garden.',
  'hero-premium-luxusimmobilien': 'Employee mopping the light limestone floor in the entrance hall of a villa with an oak staircase.',
  'hero-premium-privatjet': 'Employee vacuuming the carpet between the leather seats in the cabin of a business jet.',
  'hero-premium-yacht': 'Crew member scrubbing the teak deck of a motor yacht in a harbour on a lake in Central Switzerland.',
  'hero-einzugsgebiet': 'View from a hillside over a valley with residential areas, businesses and railway lines to a lake and the mountains of Central Switzerland.',
  'hero-ueber-uns': 'Employee preparing the cleaning trolley for the day in the supply room, with shelves of cloths and equipment beside her.',
  'hero-kontakt': 'Small office with a desk, laptop, telephone, notepad and coffee cup, ready for the next call.',
  'hero-ratgeber': 'Freshly mopped basement corridor of a block of flats with wooden storage compartments; at the end an employee works with a mop.',
  'hero-artikel-reinigungsfirma': 'During a site visit a client shows an employee with a clipboard around the office premises.',
  'hero-artikel-kosten': 'Hands pointing at a floor plan on a wooden table, next to a folding rule, notepad and coffee cup.',
  'hero-recht': 'Quiet, clean stairwell of a block of flats with artificial stone steps and a window.',
  'hero-kanton-luzern': 'Lakeshore in Central Switzerland with a promenade, boats, houses on the hillside and mountains in the background.',
  'hero-kanton-zug': 'Lakeside promenade in Central Switzerland with residential buildings on the shore and a mountain across the lake.',
  'hero-kanton-aargau': 'Small town on a river with old town houses, a church tower, a stone bridge and wooded hills.',
  'hero-kanton-nidwalden': 'Village in Central Switzerland with a church, meadows and mountains, a lake in the background.',
  'hero-kanton-obwalden': 'Lakeside village in Central Switzerland with a church, meadows and mountains reflected in the calm water.',
  'detail-unterhaltsreinigung': 'Hand in a grey glove wiping the wooden handrail in the stairwell with a microfibre cloth.',
  'detail-bueroreinigung': 'Gloved hands emptying a waste-paper basket from a workstation into the rubbish bag on the cleaning trolley.',
  'detail-umzugsreinigung': 'Hands in yellow gloves cleaning the inside of an oven during an end-of-tenancy clean, the dirty baking tray in front.',
  'detail-baureinigung': 'Hands in work gloves peeling the protective film off a new window frame, with a glass scraper on the sill.',
  'detail-fenster-fassaden': 'Hands drawing a squeegee across a soaped window pane, the strip washer in the other hand.',
  'detail-industrie-hallen': 'Scrubber dryer cleaning the concrete floor between pallet racks, guided by the employee at the handle.',
  'detail-hauswartung': 'Caretaker changing the bulb in the ceiling light of the laundry room of a block of flats.',
  'detail-aussen-gruenflaechen': 'Employee raking autumn leaves on the lawn of a housing estate, with the green waste bin beside him.',
  'detail-facility-services': 'Hands ticking off a checklist in the supply store, with shelves of cloths and cleaning products behind.',
  'detail-premium-luxusimmobilien': 'Hands in black gloves caring for a natural stone washbasin next to a brass tap.',
  'detail-premium-privatjet': 'Gloved hands wiping the burr wood table in the cabin of a business jet.',
  'detail-premium-yacht': 'Gloved hands polishing a stainless steel cleat on the teak deck of a yacht in the harbour.',
  'hero-grundreinigung': 'Employee guiding a single-disc machine over the natural stone floor of an entrance hall, with a wet vacuum and a bucket beside her.',
  'detail-grundreinigung': 'Single-disc machine working with cleaning foam on a worn natural stone floor.',
  // Additional motifs per service and premium page (E84): second zigzag row and FAQ section
  'szene-unterhaltsreinigung': 'Cleaner wiping the stainless steel wall of the lift car in a block of flats, with the cleaning trolley in front of the lift.',
  'frage-unterhaltsreinigung': 'A property manager shows an employee with a clipboard the cleaning room in the basement where equipment and cleaning products can be kept.',
  'szene-bueroreinigung': 'Employee wiping the armrests of the chairs in a practice waiting room in the evening, with the reception desk and cleaning trolley nearby.',
  'frage-bueroreinigung': 'At the office entrance a client hands an employee with a clipboard the access badge for the cleaning.',
  'szene-sonderreinigungen': 'Employee kneeling to scrub the floor grout in front of the toilet cubicles of a tiled washroom, with a bucket and spray bottle beside her.',
  'frage-sonderreinigungen': 'During a site visit to an empty office floor an employee checks the worn floor covering while the property manager looks on.',
  'szene-umzugsreinigung': 'During an end-of-tenancy clean an employee scrubs the balcony floor of the empty flat, with a bucket and a dustpan of leaves beside her.',
  'frage-umzugsreinigung': 'At the handover inspection in the empty flat the property manager points at the window frame and the employee notes it on her clipboard.',
  'szene-baureinigung': 'Rough cleaning in a shell building: an employee sweeps up building debris between concrete walls, with a bucket and wheelbarrow nearby.',
  'frage-baureinigung': 'A site manager with a helmet and a rolled-up plan shows an employee with a clipboard the corridor of a new building before handover.',
  'szene-fenster-und-fassadenreinigung': 'Window cleaner standing on the lawn cleaning a first-floor window with a water-fed telescopic pole, the hose running from the pure-water unit to the brush.',
  'frage-fenster-und-fassadenreinigung': 'At an office appointment an employee opens the window sash to check whether the outside of the pane can be reached from inside, the client’s hand on the frame.',
  'szene-industrie-und-hallenreinigung': 'Employee vacuuming metal chips around a machine in a production hall with an industrial vacuum cleaner.',
  'frage-industrie-und-hallenreinigung': 'On a walk through the hall an employee in a high-visibility vest measures the walkways with a measuring wheel, the production manager walking beside her.',
  'szene-hauswartung': 'Caretaker pulling a waste container from the collection point of a housing estate to the road in the morning.',
  'frage-hauswartung': 'During a walk-round a representative of the owners points out the light at the building entrance to the caretaker.',
  'szene-aussen-und-gruenflaechenpflege': 'Employee trimming the hedge along a path in a housing estate, the clippings falling onto a tarpaulin, with a wheelbarrow beside him.',
  'frage-aussen-und-gruenflaechenpflege': 'Before trimming, an employee checks the hedge for bird nests while the property manager looks on, the hedge trimmer lying on the path.',
  'szene-facility-services': 'Outside the entrance of a commercial building a caretaker sweeps leaves from the forecourt while a colleague cleans the glass door.',
  'frage-facility-services': 'At the meeting table a client and an employee go through the site plan of the property with its buildings, paths and green areas.',
  'szene-luxusimmobilien': 'Employee wiping the matt fronts of the kitchen island in a villa with a microfibre cloth.',
  'frage-luxusimmobilien': 'During a walk-round of a villa the owner shows the employee the walnut chest of drawers and the paintings.',
  'szene-privatjet': 'Employee cleaning the high-gloss wood cabinets in the galley of a business jet, with the cabin and its leather seats behind.',
  'frage-privatjet': 'In the hangar lounge a representative of the flight operator and an employee plan the cabin cleaning, with the aircraft visible through the window.',
  'szene-yacht': 'From the jetty an employee washes pollen off the hull of a motor yacht with a soft brush.',
  'frage-yacht': 'Inspection at the mooring: the owner shows an employee on the jetty the teak deck of his motor yacht.',
  // Title images of new guide articles (wave 2)
  'hero-artikel-pflichtenheft': 'Caretaker with a clipboard checking the ceiling light on an inspection round in the stairwell of a block of flats.',
  'hero-artikel-wohnungsabgabe': 'Empty, freshly cleaned rented flat with parquet flooring before the handover inspection, the keys on the window sill.',
  'hero-artikel-bodenarten': 'Threshold where natural stone meets linoleum and parquet, with a flat mop and a cleaning trolley beside it.',
}
