import type { ImageKey } from '../../shared/images'

/** Alt texts for the images (E80). Heroes are mood images and stay hidden from screen readers; all other images carry this text. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Cleaner seen from behind mopping the wet granite floor in the entrance of a block of flats with letterboxes and a lift, the cleaning trolley beside her.',
  'hero-leistungen': 'Fully equipped cleaning trolley in the linoleum corridor of a school building; further back an employee cleans a door handle.',
  'hero-unterhaltsreinigung': 'Cleaner seen from behind mopping the artificial stone stairs in the stairwell of a block of flats, with a red bucket and a shoe rack beside her.',
  'hero-bueroreinigung': 'Cleaner vacuuming the carpet between the workstations of an open-plan office in the evening.',
  'hero-sonderreinigungen': 'End-of-tenancy cleaning in an empty rented flat: an employee cleans the kitchen fronts, the oven stands open, with a bucket and ladder in front.',
  'hero-baureinigung': 'Employee vacuuming construction dust from the floor of a new build before handover, with protective film, a bucket and a scraper beside him.',
  'hero-fenster-fassaden': 'Window cleaner on a stepladder washing the large pane of an office building with a strip washer.',
  'hero-industrie-hallen': 'Employee cleaning the concrete floor of a warehouse between pallet racks with a scrubber dryer.',
  'hero-hauswartung': 'Caretaker on an inspection round checking a pressure gauge in the boiler room of a block of flats, his toolbox beside him.',
  'hero-aussen-gruenflaechen': 'Employee mowing the lawn of a housing estate, with a wheelbarrow of grass cuttings and a rake beside him.',
  'hero-facility-services': 'An employee with a checklist and a client walk together through the corridor of an office building during a handover.',
  'hero-premium': 'Employee caring for a wooden sideboard in the living room of a villa with a natural stone floor, with a view into the garden.',
  'hero-premium-luxusimmobilien': 'Employee mopping the light limestone floor in the entrance hall of a villa with an oak staircase.',
  'hero-premium-privatjet': 'Employee vacuuming the carpet between the leather seats in the cabin of a business jet.',
  'hero-premium-yacht': 'Crew member scrubbing the teak deck of a motor yacht in a harbour on Lake Lucerne.',
  'hero-einzugsgebiet': 'View from a hillside over the Reuss valley with residential areas, businesses and railway lines to the lake and Mount Pilatus.',
  'hero-ueber-uns': 'Employee preparing the cleaning trolley for the day in the supply room, with shelves of cloths and equipment beside her.',
  'hero-kontakt': 'Small office with a desk, laptop, telephone, notepad and coffee cup, ready for the next call.',
  'hero-ratgeber': 'Freshly mopped basement corridor of a block of flats with wooden storage compartments; at the end an employee works with a mop.',
  'hero-artikel-reinigungsfirma': 'During a site visit a client shows an employee with a clipboard around the office premises.',
  'hero-artikel-kosten': 'Hands pointing at a floor plan on a wooden table, next to a folding rule, notepad and coffee cup.',
  'hero-recht': 'Quiet, clean stairwell of a block of flats with artificial stone steps and a window.',
  'hero-kanton-luzern': 'Lakeshore in Lucerne with a promenade, boats, houses on the hillside and Mount Pilatus in the background.',
  'hero-kanton-zug': 'Lakeside promenade on Lake Zug with residential buildings on the shore and the Rigi across the lake.',
  'hero-kanton-aargau': 'Small town on the Aare with old town houses, a church tower, a stone bridge and the Jura hills.',
  'hero-kanton-nidwalden': 'Village in Nidwalden with a church, meadows and mountains, Lake Lucerne in the background.',
  'hero-kanton-obwalden': 'Village on Lake Sarnen in Obwalden with a church, meadows and mountains reflected in the calm water.',
  'detail-unterhaltsreinigung': 'Hand in a grey glove wiping the wooden handrail in the stairwell with a microfibre cloth.',
  'detail-bueroreinigung': 'Gloved hands emptying a waste-paper basket from a workstation into the rubbish bag on the cleaning trolley.',
  'detail-sonderreinigungen': 'Hands in yellow gloves cleaning the inside of an oven during an end-of-tenancy clean, the dirty baking tray in front.',
  'detail-baureinigung': 'Hands in work gloves peeling the protective film off a new window frame, with a glass scraper on the sill.',
  'detail-fenster-fassaden': 'Hands drawing a squeegee across a soaped window pane, the strip washer in the other hand.',
  'detail-industrie-hallen': 'Scrubber dryer cleaning the concrete floor between pallet racks, guided by the employee at the handle.',
  'detail-hauswartung': 'Caretaker changing the bulb in the ceiling light of the laundry room of a block of flats.',
  'detail-aussen-gruenflaechen': 'Employee raking autumn leaves on the lawn of a housing estate, with the green waste bin beside him.',
  'detail-facility-services': 'Hands ticking off a checklist in the supply store, with shelves of cloths and cleaning products behind.',
  'detail-premium-luxusimmobilien': 'Hands in black gloves caring for a natural stone washbasin next to a brass tap.',
  'detail-premium-privatjet': 'Gloved hands wiping the burr wood table in the cabin of a business jet.',
  'detail-premium-yacht': 'Gloved hands polishing a stainless steel cleat on the teak deck of a yacht in the harbour.',
  'hero-grundreinigung': 'Employee guiding a single-disc machine over the natural stone floor of an entrance hall, with a wet vacuum and a bucket beside her.',
  'detail-grundreinigung': 'Single-disc machine working with cleaning foam on a worn natural stone floor.',
}
