import type { ImageKey } from '../../shared/images'

/** Alt-Texte der Bilder (E80). Heros sind Stimmung und bleiben für Screenreader aus, alle übrigen Bilder tragen diesen Text. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Reinigungskraft von hinten wischt den nassen Granitboden im Eingangsbereich eines Mehrfamilienhauses mit Briefkästen und Lift, daneben der Reinigungswagen.',
  'hero-leistungen': 'Voll ausgestatteter Reinigungswagen im Linoleumflur eines Schulhauses, weiter hinten reinigt eine Mitarbeiterin eine Türklinke.',
  'hero-unterhaltsreinigung': 'Reinigungskraft von hinten wischt die Kunststeintreppe im Treppenhaus eines Mehrfamilienhauses, daneben ein roter Eimer und ein Schuhregal.',
  'hero-bueroreinigung': 'Reinigungskraft saugt am Abend den Teppichboden zwischen den Arbeitsplätzen eines Grossraumbüros.',
  'hero-umzugsreinigung': 'Endreinigung in einer leeren Mietwohnung: Eine Mitarbeiterin reinigt die Küchenfronten, der Backofen steht offen, davor Eimer und Leiter.',
  'hero-baureinigung': 'Mitarbeiter saugt im Neubau vor der Übergabe Baustaub vom Boden, daneben Schutzfolie, Eimer und Spachtel.',
  'hero-fenster-fassaden': 'Fensterreiniger auf einer Bockleiter wäscht die grosse Scheibe eines Bürogebäudes mit dem Einwascher.',
  'hero-industrie-hallen': 'Mitarbeiter reinigt mit einer Scheuersaugmaschine den Betonboden einer Lagerhalle zwischen Palettenregalen.',
  'hero-hauswartung': 'Hauswart auf dem Kontrollgang prüft im Heizungsraum eines Mehrfamilienhauses ein Manometer, daneben sein Werkzeugkoffer.',
  'hero-aussen-gruenflaechen': 'Mitarbeiter mäht den Rasen einer Wohnsiedlung, daneben eine Schubkarre mit Grasschnitt und Rechen.',
  'hero-facility-services': 'Mitarbeiterin mit Checkliste und eine Kundin gehen bei einer Übergabe gemeinsam durch den Flur eines Bürogebäudes.',
  'hero-premium': 'Mitarbeiterin pflegt im Wohnraum einer Villa mit Natursteinboden ein Sideboard aus Holz, der Blick geht in den Garten.',
  'hero-premium-luxusimmobilien': 'Mitarbeiterin wischt den hellen Kalksteinboden in der Eingangshalle einer Villa mit Eichentreppe.',
  'hero-premium-privatjet': 'Mitarbeiterin saugt in der Kabine eines Geschäftsreiseflugzeugs den Teppich zwischen den Ledersitzen.',
  'hero-premium-yacht': 'Crewmitglied schrubbt das Teakdeck einer Motoryacht in einem Hafen an einem See in der Zentralschweiz.',
  'hero-einzugsgebiet': 'Blick vom Hang über ein Tal mit Wohnquartieren, Gewerbe und Bahnanlagen bis zu einem See und den Bergen der Zentralschweiz.',
  'hero-ueber-uns': 'Mitarbeiterin bereitet im Materialraum den Reinigungswagen für den Tag vor, daneben Regale mit Tüchern und Geräten.',
  'hero-kontakt': 'Kleines Büro mit Schreibtisch, Laptop, Telefon, Notizblock und Kaffeetasse, bereit für den nächsten Anruf.',
  'hero-ratgeber': 'Frisch gewischter Kellergang eines Mehrfamilienhauses mit Holzabteilen, am Ende arbeitet eine Mitarbeiterin mit dem Mopp.',
  'hero-artikel-reinigungsfirma': 'Bei einer Besichtigung zeigt ein Kunde einer Mitarbeiterin mit Klemmbrett die Büroräume.',
  'hero-artikel-kosten': 'Hände zeigen auf einen Grundriss auf einem Holztisch, daneben Meterstab, Notizblock und Kaffeetasse.',
  'hero-recht': 'Ruhiges, sauberes Treppenhaus eines Mehrfamilienhauses mit Kunststeinstufen und Fenster.',
  'hero-kanton-luzern': 'Seeufer in der Zentralschweiz mit Promenade, Booten, Wohnhäusern am Hang und Bergen im Hintergrund.',
  'hero-kanton-zug': 'Seepromenade in der Zentralschweiz mit Wohnbauten am Ufer und einem Berg auf der anderen Seeseite.',
  'hero-kanton-aargau': 'Kleinstadt an einem Fluss mit Altstadthäusern, Kirchturm, Steinbrücke und bewaldeten Hügeln.',
  'hero-kanton-nidwalden': 'Dorf in der Zentralschweiz mit Kirche, Wiesen und Bergen, im Hintergrund ein See.',
  'hero-kanton-obwalden': 'Dorf am See in der Zentralschweiz mit Kirche, Wiesen und Bergen, die sich im ruhigen Wasser spiegeln.',
  'detail-unterhaltsreinigung': 'Hand im grauen Handschuh wischt mit einem Mikrofasertuch den Holzhandlauf im Treppenhaus.',
  'detail-bueroreinigung': 'Hände in Handschuhen leeren einen Papierkorb vom Arbeitsplatz in den Abfallsack am Reinigungswagen.',
  'detail-umzugsreinigung': 'Hände in gelben Handschuhen reinigen bei der Endreinigung das Innere eines Backofens, davor das verschmutzte Blech.',
  'detail-baureinigung': 'Hände in Arbeitshandschuhen ziehen die Schutzfolie vom neuen Fensterrahmen, auf dem Sims liegt ein Glasschaber.',
  'detail-fenster-fassaden': 'Hände ziehen mit dem Abzieher die eingeseifte Fensterscheibe ab, in der anderen Hand der Einwascher.',
  'detail-industrie-hallen': 'Mitarbeiter in grauer Arbeitskleidung und Handschuhen wischt die Aussenseite eines geschlossenen Maschinengehäuses mit einem blauen Tuch.',
  'detail-hauswartung': 'Hauswart wechselt in der Waschküche eines Mehrfamilienhauses die Glühbirne an der Deckenlampe.',
  'detail-aussen-gruenflaechen': 'Mitarbeiter recht Herbstlaub auf dem Rasen einer Wohnsiedlung zusammen, daneben der Grüncontainer.',
  'detail-facility-services': 'Hände haken im Materiallager eine Checkliste ab, dahinter Regale mit Tüchern und Reinigungsmitteln.',
  'detail-premium-luxusimmobilien': 'Hände in schwarzen Handschuhen pflegen den Natursteinwaschtisch neben einer Messingarmatur.',
  'detail-premium-privatjet': 'Hände in Handschuhen wischen den Wurzelholztisch in der Kabine eines Geschäftsreiseflugzeugs.',
  'detail-premium-yacht': 'Hände in Handschuhen polieren eine Edelstahlklampe auf dem Teakdeck einer Yacht im Hafen.',
  'hero-grundreinigung': 'Mitarbeiterin führt eine Einscheibenmaschine über den Natursteinboden einer Eingangshalle, daneben ein Nasssauger und ein Eimer.',
  'detail-grundreinigung': 'Einscheibenmaschine arbeitet mit Reinigungsschaum auf einem abgenutzten Natursteinboden.',
  // Zusätzliche Motive je Leistungs- und Premiumseite (E84): zweite Zickzack-Zeile und Fragen-Bereich
  'szene-unterhaltsreinigung': 'Reinigungskraft wischt im Mehrfamilienhaus die Edelstahlwand der Liftkabine, der Reinigungswagen steht vor dem Lift.',
  'frage-unterhaltsreinigung': 'Verwalterin zeigt einer Mitarbeiterin mit Klemmbrett den Putzraum im Keller, in dem Geräte und Reinigungsmittel stehen dürfen.',
  'szene-bueroreinigung': 'Mitarbeiterin wischt am Abend im Wartezimmer einer Praxis die Armlehnen der Stühle ab, daneben Empfangstheke und Reinigungswagen.',
  'frage-bueroreinigung': 'Am Büroeingang übergibt ein Kunde einer Mitarbeiterin mit Klemmbrett den Zutrittsbadge für die Reinigung.',
  'szene-sonderreinigungen': 'Mitarbeiterin schrubbt kniend die Bodenfugen vor den WC-Kabinen eines gefliesten Sanitärraums, daneben Eimer und Sprühflasche.',
  'frage-sonderreinigungen': 'Bei der Besichtigung einer leeren Bürofläche prüft eine Mitarbeiterin den abgenutzten Bodenbelag, der Verwalter schaut zu.',
  'szene-umzugsreinigung': 'Mitarbeiterin schrubbt bei der Endreinigung den Balkonboden der leeren Wohnung, daneben Eimer und Kehrschaufel mit Laub.',
  'frage-umzugsreinigung': 'Bei der Abnahme in der leeren Wohnung zeigt die Verwalterin auf den Fensterrahmen, die Mitarbeiterin notiert es auf dem Klemmbrett.',
  'szene-baureinigung': 'Grobreinigung im Rohbau: Mitarbeiter wischt Bauschutt zwischen Betonwänden zusammen, daneben Eimer und Schubkarre.',
  'frage-baureinigung': 'Bauleiter mit Helm und gerolltem Plan zeigt einer Mitarbeiterin mit Klemmbrett den Flur eines Neubaus vor der Übergabe.',
  'szene-fenster-und-fassadenreinigung': 'Fensterreiniger reinigt vom Rasen aus mit einer wasserführenden Teleskopstange ein Fenster im ersten Stock, der Schlauch läuft vom Reinwassergerät bis zur Bürste.',
  'frage-fenster-und-fassadenreinigung': 'Beim Termin im Büro öffnet ein Mitarbeiter den Fensterflügel und prüft, ob sich die Aussenseite der Scheibe von innen erreichen lässt, daneben die Hand des Kunden am Rahmen.',
  'szene-industrie-und-hallenreinigung': 'Mitarbeiter saugt in einer Produktionshalle Metallspäne rund um eine Maschine mit dem Industriesauger.',
  'frage-industrie-und-hallenreinigung': 'Beim Rundgang in der Halle misst eine Mitarbeiterin in Warnweste mit dem Messrad die Verkehrswege, der Betriebsleiter geht neben ihr.',
  'szene-hauswartung': 'Hauswart zieht am Morgen einen Abfallcontainer vom Sammelplatz einer Wohnsiedlung zur Strasse.',
  'frage-hauswartung': 'Beim Rundgang zeigt ein Vertreter der Eigentümerschaft dem Hauswart die Leuchte am Hauseingang.',
  'szene-aussen-und-gruenflaechenpflege': 'Mitarbeiter schneidet die Hecke entlang eines Wegs in einer Wohnsiedlung, der Schnitt fällt auf eine Plane, daneben die Schubkarre.',
  'frage-aussen-und-gruenflaechenpflege': 'Vor dem Heckenschnitt sieht eine Mitarbeiterin in der Hecke nach Vogelnestern, die Verwalterin schaut zu, der Heckenschneider liegt am Weg.',
  'szene-facility-services': 'Vor dem Eingang eines Geschäftshauses wischt ein Hauswart Laub vom Vorplatz, daneben reinigt eine Kollegin die Glastür.',
  'frage-facility-services': 'Am Besprechungstisch gehen ein Kunde und eine Mitarbeiterin den Lageplan der Liegenschaft durch, mit Gebäuden, Wegen und Grünflächen.',
  'szene-luxusimmobilien': 'Mitarbeiterin wischt in der Küche einer Villa die matten Fronten der Kochinsel mit einem weichen Tuch.',
  'frage-luxusimmobilien': 'Beim Rundgang durch eine Villa zeigt die Eigentümerin der Mitarbeiterin die Kommode aus Nussbaum und die Bilder.',
  'szene-privatjet': 'Mitarbeiterin reinigt in der Bordküche eines Geschäftsreiseflugzeugs die Schränke aus Hochglanzholz, dahinter die Kabine mit Ledersitzen.',
  'frage-privatjet': 'In der Lounge am Hangar planen ein Vertreter des Flugbetriebs und eine Mitarbeiterin die Kabinenreinigung, durch die Scheibe sieht man das Flugzeug.',
  'szene-yacht': 'Mitarbeiterin wäscht vom Steg aus mit einer weichen Bürste den Blütenstaub vom Rumpf einer Motoryacht.',
  'frage-yacht': 'Besichtigung am Liegeplatz: Der Eigner zeigt einem Mitarbeiter auf dem Steg das Teakdeck seiner Motoryacht.',
  // Titelbilder neuer Ratgeber-Artikel (Welle 2)
  'hero-artikel-pflichtenheft': 'Hauswart mit Klemmbrett prüft auf dem Kontrollgang im Treppenhaus eines Mehrfamilienhauses die Deckenleuchte.',
  'hero-artikel-wohnungsabgabe': 'Leere, frisch gereinigte Mietwohnung mit Parkett vor der Abnahme, auf dem Fenstersims liegen die Schlüssel.',
  'hero-artikel-bodenarten': 'Türschwelle, an der Naturstein auf Linoleum und Parkett trifft, daneben Wischmopp und Reinigungswagen.',
}
