import type { ImageKey } from '../../shared/images'

/** Alt-Texte der Bilder (E80). Heros sind Stimmung und bleiben für Screenreader aus, alle übrigen Bilder tragen diesen Text. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Reinigungskraft von hinten wischt den nassen Granitboden im Eingangsbereich eines Mehrfamilienhauses mit Briefkästen und Lift, daneben der Reinigungswagen.',
  'hero-leistungen': 'Voll ausgestatteter Reinigungswagen im Linoleumflur eines Schulhauses, weiter hinten reinigt eine Mitarbeiterin eine Türklinke.',
  'hero-unterhaltsreinigung': 'Reinigungskraft von hinten wischt die Kunststeintreppe im Treppenhaus eines Mehrfamilienhauses, daneben ein roter Eimer und ein Schuhregal.',
  'hero-bueroreinigung': 'Reinigungskraft saugt am Abend den Teppichboden zwischen den Arbeitsplätzen eines Grossraumbüros.',
  'hero-sonderreinigungen': 'Endreinigung in einer leeren Mietwohnung: Eine Mitarbeiterin reinigt die Küchenfronten, der Backofen steht offen, davor Eimer und Leiter.',
  'hero-baureinigung': 'Mitarbeiter saugt im Neubau vor der Übergabe Baustaub vom Boden, daneben Schutzfolie, Eimer und Spachtel.',
  'hero-fenster-fassaden': 'Fensterreiniger auf einer Bockleiter wäscht die grosse Scheibe eines Bürogebäudes mit dem Einwascher.',
  'hero-industrie-hallen': 'Mitarbeiter reinigt mit einer Scheuersaugmaschine den Betonboden einer Lagerhalle zwischen Palettenregalen.',
  'hero-hauswartung': 'Hauswart auf dem Kontrollgang prüft im Heizungsraum eines Mehrfamilienhauses ein Manometer, daneben sein Werkzeugkoffer.',
  'hero-aussen-gruenflaechen': 'Mitarbeiter mäht den Rasen einer Wohnsiedlung, daneben eine Schubkarre mit Grasschnitt und Rechen.',
  'hero-facility-services': 'Mitarbeiterin mit Checkliste und eine Kundin gehen bei einer Übergabe gemeinsam durch den Flur eines Bürogebäudes.',
  'hero-premium': 'Mitarbeiterin pflegt im Wohnraum einer Villa mit Natursteinboden ein Sideboard aus Holz, der Blick geht in den Garten.',
  'hero-premium-luxusimmobilien': 'Mitarbeiterin wischt den hellen Kalksteinboden in der Eingangshalle einer Villa mit Eichentreppe.',
  'hero-premium-privatjet': 'Mitarbeiterin saugt in der Kabine eines Geschäftsreiseflugzeugs den Teppich zwischen den Ledersitzen.',
  'hero-premium-yacht': 'Crewmitglied schrubbt das Teakdeck einer Motoryacht in einem Hafen am Vierwaldstättersee.',
  'hero-einzugsgebiet': 'Blick vom Hang über das Reusstal mit Wohnquartieren, Gewerbe und Bahnanlagen bis zum See und zum Pilatus.',
  'hero-ueber-uns': 'Mitarbeiterin bereitet im Materialraum den Reinigungswagen für den Tag vor, daneben Regale mit Tüchern und Geräten.',
  'hero-kontakt': 'Kleines Büro mit Schreibtisch, Laptop, Telefon, Notizblock und Kaffeetasse, bereit für den nächsten Anruf.',
  'hero-ratgeber': 'Frisch gewischter Kellergang eines Mehrfamilienhauses mit Holzabteilen, am Ende arbeitet eine Mitarbeiterin mit dem Mopp.',
  'hero-artikel-reinigungsfirma': 'Bei einer Besichtigung zeigt ein Kunde einer Mitarbeiterin mit Klemmbrett die Büroräume.',
  'hero-artikel-kosten': 'Hände zeigen auf einen Grundriss auf einem Holztisch, daneben Meterstab, Notizblock und Kaffeetasse.',
  'hero-recht': 'Ruhiges, sauberes Treppenhaus eines Mehrfamilienhauses mit Kunststeinstufen und Fenster.',
  'hero-kanton-luzern': 'Seeufer in Luzern mit Promenade, Booten, Wohnhäusern am Hang und dem Pilatus im Hintergrund.',
  'hero-kanton-zug': 'Seepromenade am Zugersee mit Wohnbauten am Ufer und der Rigi auf der anderen Seeseite.',
  'hero-kanton-aargau': 'Kleinstadt an der Aare mit Altstadthäusern, Kirchturm, Steinbrücke und Jurahügeln.',
  'hero-kanton-nidwalden': 'Dorf in Nidwalden mit Kirche, Wiesen und Bergen, im Hintergrund der Vierwaldstättersee.',
  'hero-kanton-obwalden': 'Dorf am Sarnersee in Obwalden mit Kirche, Wiesen und Bergen, die sich im ruhigen Wasser spiegeln.',
  'detail-unterhaltsreinigung': 'Hand im grauen Handschuh wischt mit einem Mikrofasertuch den Holzhandlauf im Treppenhaus.',
  'detail-bueroreinigung': 'Hände in Handschuhen leeren einen Papierkorb vom Arbeitsplatz in den Abfallsack am Reinigungswagen.',
  'detail-sonderreinigungen': 'Hände in gelben Handschuhen reinigen bei der Endreinigung das Innere eines Backofens, davor das verschmutzte Blech.',
  'detail-baureinigung': 'Hände in Arbeitshandschuhen ziehen die Schutzfolie vom neuen Fensterrahmen, auf dem Sims liegt ein Glasschaber.',
  'detail-fenster-fassaden': 'Hände ziehen mit dem Abzieher die eingeseifte Fensterscheibe ab, in der anderen Hand der Einwascher.',
  'detail-industrie-hallen': 'Scheuersaugmaschine reinigt den Betonboden zwischen Palettenregalen, der Mitarbeiter führt sie am Griff.',
  'detail-hauswartung': 'Hauswart wechselt in der Waschküche eines Mehrfamilienhauses die Glühbirne an der Deckenlampe.',
  'detail-aussen-gruenflaechen': 'Mitarbeiter recht Herbstlaub auf dem Rasen einer Wohnsiedlung zusammen, daneben der Grüncontainer.',
  'detail-facility-services': 'Hände haken im Materiallager eine Checkliste ab, dahinter Regale mit Tüchern und Reinigungsmitteln.',
  'detail-premium-luxusimmobilien': 'Hände in schwarzen Handschuhen pflegen den Natursteinwaschtisch neben einer Messingarmatur.',
  'detail-premium-privatjet': 'Hände in Handschuhen wischen den Wurzelholztisch in der Kabine eines Geschäftsreiseflugzeugs.',
  'detail-premium-yacht': 'Hände in Handschuhen polieren eine Edelstahlklampe auf dem Teakdeck einer Yacht im Hafen.',
  'hero-grundreinigung': 'Mitarbeiterin führt eine Einscheibenmaschine über den Natursteinboden einer Eingangshalle, daneben ein Nasssauger und ein Eimer.',
  'detail-grundreinigung': 'Einscheibenmaschine arbeitet mit Reinigungsschaum auf einem abgenutzten Natursteinboden.',
}
