import type { ImageKey } from '../../shared/images'

/** Alt-Texte der Bilder (E80). Heros sind Stimmung und bleiben für Screenreader aus, alle übrigen Bilder tragen diesen Text. */
export const bilder: Record<ImageKey, string> = {
  'hero-start': 'Helle Eingangshalle mit Steintreppe, eine Reinigungskraft in dunkelgrauer Arbeitskleidung wischt von hinten gesehen den glänzenden Terrazzoboden.',
  'hero-leistungen': 'Aufgeräumter Reinigungswagen mit Eimern, Mikrofasertüchern und Wischmopp in einem hellen Flur mit Glasfront.',
  'hero-unterhaltsreinigung': 'Reinigungskraft wischt von hinten gesehen den Boden im Treppenhaus eines Mehrfamilienhauses, daneben ein Eimer.',
  'hero-bueroreinigung': 'Leeres modernes Grossraumbüro am Abend mit aufgeräumten Arbeitsplätzen, warmem Licht und Blick auf See und Berge.',
  'hero-sonderreinigungen': 'Leere helle Wohnung bei der Endreinigung mit sauberer Kücheninsel aus Naturstein und grossen Fenstern zum See.',
  'hero-baureinigung': 'Neubau vor der Übergabe mit Baustaub auf dem Estrich, Eimern, Abzieher und grossen Glasflächen mit Blick auf See und Berge.',
  'hero-fenster-fassaden': 'Fensterreiniger von hinten reinigt eine grosse Glasfassade mit einer Teleskopstange und Reinwasser.',
  'hero-industrie-hallen': 'Mitarbeiter mit Helm und Warnweste reinigt von hinten gesehen mit einer Scheuersaugmaschine den Boden einer grossen hellen Halle.',
  'hero-hauswartung': 'Hauswart mit Werkzeugkoffer von hinten auf dem Kontrollgang durch den begrünten Innenhof einer gepflegten Wohnanlage.',
  'hero-aussen-gruenflaechen': 'Frisch geschnittene Hecke, Kiesweg mit Herbstlaub, Rasen und ein Laubrechen an einer gepflegten Liegenschaft am See.',
  'hero-facility-services': 'Hände mit Klemmbrett und Stift bei einer Übergabe, im Hintergrund Reinigungsgeräte und eine Mitarbeiterin von hinten.',
  'hero-premium': 'Wohnraum einer Villa mit Natursteinboden, Sofa in warmen Tönen und Blick auf einen See mit Bergen in der Abendsonne.',
  'hero-premium-luxusimmobilien': 'Hände in schwarzen Handschuhen polieren mit einem Mikrofasertuch einen dunklen Natursteinboden vor Fischgratparkett.',
  'hero-premium-privatjet': 'Leere Kabine eines Privatjets mit cremefarbenen Ledersitzen, Wurzelholz und Teppich, durch die Fenster Alpengipfel.',
  'hero-premium-yacht': 'Teakdeck einer Motoryacht mit hellen Polstern und Edelstahlreling auf einem ruhigen See vor Bergen im Abendlicht.',
  'hero-einzugsgebiet': 'Luftbild der Zentralschweiz im Morgenlicht mit langem See, Dörfern am Ufer, Nebel und Bergen.',
  'hero-ueber-uns': 'Sorgfältig bereitgestellte Reinigungsmittel, Tücher, Bürsten, Eimer und Wischmopp auf einem Holzregal in einem hellen Raum.',
  'hero-kontakt': 'Leere helle Eingangshalle eines Bürogebäudes mit Steinboden, Holzverkleidung und Glastür.',
  'hero-ratgeber': 'Sonniger heller Korridor mit glänzend poliertem Boden und Blick auf einen See am Ende.',
  'hero-artikel-reinigungsfirma': 'Hände mit Klemmbrett und Stift bei einer Besichtigung in einem hellen Treppenhaus.',
  'hero-artikel-kosten': 'Grundriss auf einem dunklen Holztisch mit Meterstab und Stift, dazu Materialmuster aus Stein und Holz.',
  'hero-recht': 'Weisse Steintreppe mit klaren Licht- und Schattenlinien an einer weissen Wand.',
  'hero-kanton-luzern': 'Uferlandschaft am Vierwaldstättersee mit Schilf, Steinen am Ufer und bewaldeten Bergen im Morgenlicht.',
  'hero-kanton-zug': 'Zugersee mit moderner Wohnbebauung am Ufer, Bootssteg und Bergen im Hintergrund.',
  'hero-kanton-aargau': 'Die Aare fliesst durch grüne Landschaft, am Ufer eine gepflegte Siedlung mit Kirchturm.',
  'hero-kanton-nidwalden': 'Seeufer in Nidwalden mit Dorf, Bootssteg und steilen grünen Bergen, die sich im ruhigen Wasser spiegeln.',
  'hero-kanton-obwalden': 'Sarnersee in Obwalden mit Wiesen, Häusern am Hang und Bergen in Richtung Engelberg im Gegenlicht.',
  'detail-unterhaltsreinigung': 'Hände in grauen Handschuhen reinigen die Edelstahltür eines Lifts im Eingangsbereich eines Wohnhauses.',
  'detail-bueroreinigung': 'Saubere Teeküche im Büro mit Holzfronten, heller Arbeitsplatte, Tassen und Pflanzen.',
  'detail-sonderreinigungen': 'Hände in Handschuhen reinigen bei einer Grundreinigung Fensterrahmen und Glas mit einem Mikrofasertuch.',
  'detail-baureinigung': 'Hände in Handschuhen wischen Baustaub von einer Glasscheibe, dahinter eine Baustelle mit Gerüst und See.',
  'detail-fenster-fassaden': 'Nahaufnahme eines Fensterwischers, der eine Glasscheibe abzieht, im Hintergrund See und Berge.',
  'detail-industrie-hallen': 'Hände in Arbeitshandschuhen reinigen die Edelstahloberfläche einer Maschine in einer Produktionshalle.',
  'detail-hauswartung': 'Ordentliche Waschküche einer Wohnanlage mit drei Waschmaschinen, Wäscheständer, Korb und Regal.',
  'detail-aussen-gruenflaechen': 'Hände in Arbeitshandschuhen schneiden mit einer Heckenschere eine grüne Buchenhecke.',
  'detail-facility-services': 'Hände haken auf einem Klemmbrett eine Checkliste ab, im Hintergrund Reinigungswagen und Regal.',
  'detail-premium-luxusimmobilien': 'Hände in schwarzen Handschuhen pflegen einen Waschtisch aus dunklem Naturstein neben einer Messingarmatur.',
  'detail-premium-privatjet': 'Hände in hellen Handschuhen pflegen mit einem weichen Tuch den Ledersitz in einem Privatjet.',
  'detail-premium-yacht': 'Hände in Handschuhen polieren die Edelstahlreling neben hellen Polstern an Bord einer Yacht auf einem See.',
}
